### ISSUE TITLE
Status Codes, Status Codes everywhere

### ISSUE THREAD

**Issue by HoneyryderChuck** [puma/puma#1133] opened 2016-11-14 12:56 UTC
Check this out:

https://github.com/puma/puma/blob/f5f23aaac7aaccff1b6b138d93dd4b1755ebf1c2/lib/puma/server.rb#L747

Works quite well, although it's a repetition of [rack](https://github.com/rack/rack/blob/4b33af1c80c822cbcbb69113ff1e54f9454921c1/lib/rack/utils.rb#L585-L592)

I've also checked webrick, and it also has it's own map of status code to reason. In fact, I'd say that every server implementation has it.

This is quite tricky, as I don't know theoretically which one should be the source of knowledge on that. It definitely doesn't seem to belong to `rack`, as it shouldn't have any knowledge of http semantics (http reason seems to be server-only). However, repeating what's already available on the standard library seems to be not a good approach. Problem is, [webrick has less keys than rack and puma](https://github.com/nahi/ruby/blob/webrick_trunk/lib/webrick/httpstatus.rb#L56-L97). 

This does seem to be something that should/could be centralized, maybe in ruby standard library. But what's the best approach on ensuring that the list is up-to-date?

**Comment by nateberkopec** [comment] 2016-11-14 13:47
Hm, I dunno. The datastructure isn't [that large](https://github.com/puma/puma/blob/3f66b3d7d4413f843e4e541c4d282238318c4cd2/lib/puma/const.rb#L16).

For comparison, look at the mime-types library, which is basically a huge list of constants for use by other libraries. It's enormous!

I just don't think the size of the constant is worth the effort and extraction.

**Comment by nateberkopec** [comment] 2016-11-14 14:36
Aha! I figured out why.

See https://github.com/puma/puma/commit/537bc21593182cd9c4c0079a3936d05b1f91fe14 and #705.

**Comment by TiagoCardoso1983** [comment] 2016-11-14 16:07
@nateberkopec my concern isn't memory, just correctness. Not only based on API-maintenance supports, I don't think that rack is the best place to keep http internals info, so I actually welcome that commit. As puma is the http server, that seems fine.

However, my argument was making it more "central" to ruby. I was comparing with nodejs, where `http.STATUS_CODES` is available to anyone in the runtime. Ruby also has the benefit of having an http server implementation in the standard library (and that module with status codes seems abstracted enough), but it has been slowly ignored by everyone, so that updates to new http status codes seem to get more love in rack.

**Comment by nateberkopec** [comment] 2016-11-14 16:28
Yeah, that already exists in Rack::Utils (which is where Puma's status codes are directly copy-pasted from).

The reason Puma doesn't use Rack::Utils directly is in the issues linked above.

**Comment by TiagoCardoso1983** [comment] 2016-11-14 16:37
Yes, I just agreed with you. I wasn't for reverting the commit. I just meant, webrick is always there, available. One could easily just:

 ```ruby
require "webrick/httpstatus"
puts WEBrick::HTTPStatus::StatusMessage
```

which is my proposal of the ruby version of nodejs's `http.STATUS_CODES`.

**Comment by nateberkopec** [comment] 2016-11-14 16:49
I believe that would re-open #705 if I understand it correctly, because now Puma would be replacing a rack dependency with a webrick dependency, possibly breaking Rails code reloading as mentioned in that issue. 

Also, as you already noted, the status codes in Webrick don't exactly match. If you think this is a problem, you should take it up with Ruby core.

**Comment by TiagoCardoso1983** [comment] 2016-11-14 17:06
My understanding was that #705 was caused by relying on rack. I don't know what rails does with such static variables in reloading, but it seems out of scope, as there could be workarounds. 

The question was more whether it was agreed that having these protocol standard things copy-pasted in many projects is a pattern to maintain, or whether there is openness and motivation to write once/share everywhere. If I'm doing yet another http server, should I just copy paste this hash? I can, but do I have to? If so, where from? puma? rack? 

I can indeed start by taking it up with ruby core and maybe make my point across, but then I still have to convince maintainers to opt in. I can always start by asking their opinion on the matter :)

**Comment by TiagoCardoso1983** [comment] 2016-11-14 17:21
https://bugs.ruby-lang.org/issues/12935

**Comment by nateberkopec** [comment] 2016-11-14 20:18
I want to dig in further to #705 and the solution there before closing this.

**Comment by nateberkopec** [comment] 2017-06-03 14:25
Looks like it's coming to a Ruby Core near you: https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/58801

We can check if this constant is defined and  use it instead of our own: https://github.com/ruby/ruby/blob/bd73d374715ae8ca6e53ebd4a32f3ae2d6542352/lib/net/http/status.rb#L21

**Comment by HoneyryderChuck** [comment] 2017-06-03 22:15
> We can check if this constant is defined and use it instead of our own

Wouldn't it be best to just require the file in ruby 2.5 or higher and always use it, and keep the file as a fallback to previous rubies?

humm, isn't this going to break if the `Net::HTTP` constant isn't defined, thereby making `net/http` a dependency?

**Comment by nateberkopec** [comment] 2017-06-03 22:27
> Wouldn't it be best to just require the file in ruby 2.5 or higher and always use it, and keep the file as a fallback to previous rubies?

That's exactly what I'm proposing.

```ruby
begin 
 require "net/http/status"
 HTTP_STATUS_CODES = Net::HTTP::STATUS_CODES
rescue LoadError
   HTTP_STATUS_CODES = # manual copy of the 2.5 codes here
end
```

**Comment by HoneyryderChuck** [comment] 2017-06-04 00:07
Sorry, understood "check if constant is defined and" as:

```ruby
defined?(Net::HTTP::STATUS_CODES) || begin
...
```

**Comment by nateberkopec** [comment] 2017-06-04 00:10
Ha yes I think I *thought* require/rescue LoadError but *wrote* is defined? Brain fart!

**Closed** 2019-02-21 00:23 UTC
Labels: easy, feature
