### ISSUE TITLE
no_tlsv1 does not work

### ISSUE THREAD

**Issue by abriel** [puma/puma#1798] opened 2019-05-17 22:05 UTC
### Steps to reproduce

1) Run puma server with no_tlsv1=true option.
```
$ bundle exec puma -C config/puma.rb 
[22179] Puma starting in cluster mode...
[22179] * Version 3.12.1 (ruby 2.4.5-p335), codename: Llamas in Pajamas
[22179] * Min threads: 0, max threads: 16
[22179] * Environment: development
[22179] * Process workers: 1
[22179] * Preloading application
[22179] * Listening on ssl://0.0.0.0:9292?key=config/67151368_localhost.key&cert=config/67151368_localhost.cert&no_tlsv1=true&ssl_cipher_list=ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-RSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384,DHE-RSA-AES128-GCM-SHA256,DHE-DSS-AES128-GCM-SHA256,DHE-RSA-AES256-GCM-SHA384,DHE-DSS-AES256-GCM-SHA384,AES128-GCM-SHA256,AES256-GCM-SHA384,ECDHE-ECDSA-AES128-SHA256,ECDHE-RSA-AES128-SHA256,ECDHE-ECDSA-AES128-SHA,ECDHE-RSA-AES128-SHA,ECDHE-ECDSA-AES256-SHA384,ECDHE-RSA-AES256-SHA384,ECDHE-ECDSA-AES256-SHA,ECDHE-RSA-AES256-SHA,DHE-RSA-AES128-SHA256,DHE-RSA-AES256-SHA256,DHE-RSA-AES128-SHA,DHE-RSA-AES256-SHA,DHE-DSS-AES128-SHA256,DHE-DSS-AES256-SHA256,DHE-DSS-AES128-SHA,DHE-DSS-AES256-SHA,AES128-SHA256,AES256-SHA256,AES128-SHA,AES256-SHA
[22179] Use Ctrl-C to stop
[22179] - Worker 0 (pid: 22212) booted, phase: 0
```

2) Try out with curl
```
$ curl -vk --tls-max 1.0 https://localhost:9292/api/v1/health
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9292 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.0 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (IN), TLS handshake, Server hello (2):
* TLSv1.0 (IN), TLS handshake, Certificate (11):
* TLSv1.0 (IN), TLS handshake, Server key exchange (12):
* TLSv1.0 (IN), TLS handshake, Server finished (14):
* TLSv1.0 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.0 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.0 (OUT), TLS handshake, Finished (20):
* TLSv1.0 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.0 / ECDHE-RSA-AES256-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=localhost
*  start date: May 16 21:17:22 2019 GMT
*  expire date: May 13 21:17:22 2029 GMT
*  issuer: CN=localhost
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /api/v1/health HTTP/1.1
> Host: localhost:9292
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 206
< 
```

### Expected behavior
Server ends up connection

### Actual behavior
Server establishes connection with TLS 1.0 and responses as usual.

### System configuration

**Ruby version**: ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]
**Grape version**: 1.0.3
**Puma version**: Version 3.12.1 (ruby 2.4.5-p335), codename: Llamas in Pajamas

**Comment by MSP-Greg** [comment] 2019-05-18 20:49
Interesting.  Using master (not the gem release), I connected with both curl & net/http. Both were forced to TLSv1 or lower.

Without `no_tlsv1=true`, both got response.  With it, both had no response/connection...

**Comment by MSP-Greg** [comment] 2019-05-19 01:28
Looking thru the code, I noticed that `ssl_cipher_list=` is actually a JRuby specific option, `ssl_cipher_filter=` is used with MRI Rubies.  It may not be clear in some of the doc, but the README does mention the distinction...

**Comment by nateberkopec** [comment] 2019-05-19 14:31
Hm, why do is that interpreter-specific?

**Comment by MSP-Greg** [comment] 2019-05-19 14:56
As long as I'm looking at it...

Nov 24 2017 - Add support for specifying ssl ciphers via :binds parameters https://github.com/puma/puma/commit/c2f6803d0097cb0501bc8f82780005dfe4babbec

**Comment by abriel** [comment] 2019-05-20 13:06
Hi @MSP-Greg, 
I am sorry. the `no_tlsv1` feature is in master only. I did not check before I blame gem version. my bad.
And thank you that pointed out about difference between `ssl_cipher_list` and `ssl_cipher_filter`.

One more question here, is cipher suite supported?
I specify `ssl_cipher_filter=TLSv1.2+FIPS:kRSA+FIPS:!eNULL:!aNULL`,
but I am still able to use "SSL connection using TLSv1.2 / CAMELLIA128-SHA256" , which is not in the list.
`openssl ciphers -v 'TLSv1.2+FIPS:kRSA+FIPS:!eNULL:!aNULL'` returns a list of ciphers belong to this suite, and then I test with a cipher non in the list using curl: `curl -vk --tls-max 1.2 --ciphers CAMELLIA128-SHA256`.
Puma respond successfully with CAMELLIA128-SHA256 and ARIA256-GCM-SHA384, but should not.
Any advise here?
Thanks.

**Comment by MSP-Greg** [comment] 2019-05-20 14:16
@abriel

No problem.  I could have checked the gem, but I didn't, so sorry about that.  I tend to work with Ruby trunk and gem/repos from master...

Re ciphers, I really haven't worked much with them, either in Puma or other SSL apps.

But, with master, I verified the cipher issue, and something does seem odd.  I can't check it until later, and I may check if Ruby OpenSSL behaves the same way...

Also, the code uses the `SSL_OP_CIPHER_SERVER_PREFERENCE` option, which is described as 'Set on servers to choose the cipher according to the server's preferences'.  But I haven't seen any docs stating how that may interact with using `SSL_CTX_set_cipher_list` or `SSL_CTX_set_ciphersuites`.

**Comment by MSP-Greg** [comment] 2019-05-20 15:40
@abriel

This might be an issue with the `ssl_cipher_filter` string, but I don't know what the issue is.

I tried:
```
ssl_cipher_filter=ECDHE-RSA-AES256-GCM-SHA384:AES256-SHA256
```

And the curl connection with `CAMELLIA128-SHA256` failed, but without succeeded.  Also, Chrome does connect with:
```
The connection to this site is encrypted and authenticated using TLS 1.2, ECDHE_RSA with P-256,
and AES_256_GCM.

-and-

All resources on this page are served securely.
```

This was with Ruby 2.4.6 and OpenSSL 1.0.2p running Puma master (all my Rubies 2.5 and later are built with OpenSSL 1.1.1).

Maybe this help....

**Comment by abriel** [comment] 2019-05-20 15:52
@MSP-Greg . Thanks! I also noticed that specifying list of exact cipher works. But cipher string suite does not work. 
We can close this ticket, because origin title is not correct. - `no_tlsv1` feaure is not released yet, but merged in master and works.
Thanks!

**Comment by MSP-Greg** [comment] 2019-05-20 16:10
@abriel 

`SSL_CTX_set_ciphersuites` is TLSv1.3 specific; I don't think it's implemented anywhere in Ruby world (Ruby OpenSSL, Puma, EventMachine, etc) yet...

Thanks.  Closing is you or a member...

**Closed** 2019-05-20 16:16 UTC
Labels: bug, has-attached-pr, ssl

**Comment by camilova** [comment] 2021-11-08 19:06
Hi, is there a way to disable support for TLS v1.1 ?

thanks
