### ISSUE TITLE
Puma leaking Temp Files for large payloads

### ISSUE THREAD

**Issue by virgoproz** [puma/puma#1187] opened 2017-01-09 21:10 UTC
Using a fairly standard Rails 4.2.X, Grape API, Puma stack, Ruby 2.3.1

In production we are seeing a leakage of large temp files containing the request body in clear (POST with large bodies). After a few days we are forced to delete these files manually (or write a hack to delete periodically). Puma should call .unlink or .delete on whatever temp file it decides to create.

**Comment by janko-m** [comment] 2017-04-30 15:24
That's weird, because Puma [does unlink created tempfiles](https://github.com/puma/puma/blob/482ea5a24abaccf33c49dc9238a22e2a9affe288/lib/puma/server.rb#L761), even in case of an error.

However, it seems there are two places where Puma creates tempfiles, in `Puma::Server#read_body` and in `Puma::Client#setup_body`, and only the one created by `Puma::Client` seems to be deleted. I don't know when does `Puma::Server#read_body` get called.

**Comment by nateberkopec** [comment] 2019-07-16 23:49
Please reopen if you can reporduce this.

**Comment by smcgivern** [comment] 2021-04-26 11:50
Because the `unlink` call happens in an `ensure`, it's possible for the tempfile to stick around if the process receives SIGKILL (or the `ensure` doesn't run for any other reason; this is just the easiest way to explain it) before that happens - say, the request is still in progress.

I created https://github.com/puma/puma/pull/2613 to cover that case, even if it wasn't the root cause of this issue.

**Comment by dentarg** [comment] 2021-07-14 17:05
With https://github.com/puma/puma/pull/2613 merged, I think we can close this again.

**Closed by dentarg** 2021-07-14 17:05 UTC
Labels: bug
