### ISSUE TITLE
IOError: stream closed from "@notify.close" when `close` is called from server.rb

### ISSUE THREAD

**Issue by henrik** [puma/puma#1293] opened 2017-05-15 06:25 UTC
We're getting an error like this every few days in a small internal service app (running Padrino, deployed to Heroku) with low amounts of traffic:

```
IOError in at_exit
IOError: stream closed

[GEM_ROOT]/gems/puma-3.8.2/lib/puma/server.rb:393 :in `close`
 [GEM_ROOT]/gems/puma-3.8.2/lib/puma/server.rb:393 :in `ensure in handle_servers`
 [GEM_ROOT]/gems/puma-3.8.2/lib/puma/server.rb:396 :in `handle_servers`
 [GEM_ROOT]/gems/puma-3.8.2/lib/puma/server.rb:325 :in `block in run`
```

Line 393 being:

```
[GEM_ROOT]/gems/puma-3.8.2/lib/puma/server.rb:393:in `close'
391       ensure
392         @check.close
>>>393         @notify.close
394 
395         if @status != :restart and @own_binder
```

I haven't dug into this, but apparently `@notify` is some IOStream that is already closed when we're trying to close it, on server shutdown.

I would guess Puma could check if it's closed already to fix that error, but that's kind of sweeping it under the rug. Any ideas what the issue could be? Something we might be doing wrong on our end?

**Comment by henrik** [comment] 2017-05-15 06:27
Might it be the same issue as this one? https://github.com/puma/puma/pull/1206

**Comment by vesan** [comment] 2017-05-19 12:07
Just letting you know that we are seeing the same problem with puma 3.8.2 & Rails 5.0.2. I don't think we have anything special in the application that would cause it but you'll never know.

We also have quite low amounts of traffic (the application is still in development).

**Comment by nateberkopec** [comment] 2017-05-29 15:11
This error never occurs on our JRuby builds. Could be MRI specific, which does point to #1206, but merging that patch didn't fix the CRuby builds, so I'm not sure.

**Comment by NickolasVashchenko** [comment] 2017-06-06 03:25
Recent MRI versions do not even have the have the "stream closed" error message for couple of months anymore, it's called now "stream closed in another thread". Please update to the most recent patch version, it most likely will resolve your issue.

**Comment by mezis** [comment] 2017-06-12 11:28
@NickolasVashchenko: the error does persist with MRI `HEAD` as of writing:

```
...vendor/bundle/ruby/2.5.0/gems/puma-3.9.1/lib/puma/server.rb:393:in `close': stream closed in another thread (IOError)
```

(after receiving a `SIGTERM`, in certain circumstances)

Here's a [travis build](https://travis-ci.org/deliveroo/routemaster/builds/241960079) where this error regularly happens, 4/5 builds, both on MRI 2.4.1 and HEAD. I don't have a reliable way to reproduce this yet I'm afraid, so the build is mostly FWIW.

**Comment by NickolasVashchenko** [comment] 2017-06-12 11:48
this seems to be a bug I've described in #1302. It's a Ruby issue, I've reported it and you can monitor it being backported here: 
https://bugs.ruby-lang.org/issues/13632

**Comment by nateberkopec** [comment] 2017-06-14 20:21
Here's @respire's proposed solution: https://github.com/respire/puma/commit/4fe40c2904433a390cab0e12ddaf631286ea66d4

**Comment by NickolasVashchenko** [comment] 2017-06-27 04:01
submitted the initial version of fix: https://github.com/puma/puma/pull/1345

**Comment by nateberkopec** [comment] 2017-07-17 15:09
Anyone experiencing this bug is advised to add https://rubygems.org/gems/stopgap_13632 to their gemfile, or wait until Ruby 2.3.5 or 2.4.2 are released, which will (probably) contain the fix for this.

**Closed by nateberkopec** 2017-07-17 15:09 UTC
Labels: bug, important!

**Comment by henrik** [comment] 2017-08-01 08:11
I added the stopgap gem to our Gemfile and deployed it yesterday, but I just saw the error again today. The exact same error as initially described. Puma 3.9.1, Ruby 2.4.1.

**Comment by NickolasVashchenko** [comment] 2017-08-01 09:25
The hooks for the stopgap gem have not yet been added in a Puma release. They are only in master branch for now.

**Comment by henrik** [comment] 2017-08-18 07:04
Puma 3.10.0 has been released and includes this fix.

**Comment by krishna-rpx** [comment] 2017-11-17 06:41
I got the same issue in Puma 3.10.0

```
ems/puma-3.10.0/lib/puma/server.rb:395:in `close`
gems/puma-3.10.0/lib/puma/server.rb:395:in `ensure in handle_servers`
gems/puma-3.10.0/lib/puma/server.rb:398:in `handle_servers`
```

**Comment by nateberkopec** [comment] 2017-11-17 18:58
@krishna-rpx Can you post the full backtrace? Also, what Ruby version?

**Comment by nateberkopec** [comment] 2017-11-17 18:58
Also, are you using https://rubygems.org/gems/stopgap_13632?

**Comment by krishna-rpx** [comment] 2017-11-21 07:57
No, I am not using stopgap gem

**Comment by krishna-rpx** [comment] 2017-11-21 07:59
Ruby version ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

Please find full backtrace here.  

`
IOError: stream closed
 [GEM_ROOT]/gems/puma-3.10.0/lib/puma/server.rb:395 :in `close`
 [GEM_ROOT]/gems/puma-3.10.0/lib/puma/server.rb:395 :in `ensure in handle_servers`
 [GEM_ROOT]/gems/puma-3.10.0/lib/puma/server.rb:398 :in `handle_servers`
 [GEM_ROOT]/gems/puma-3.10.0/lib/puma/server.rb:327 :in `block in run`
Nested Exceptions
IOError: stream closed
 [GEM_ROOT]/gems/puma-3.10.0/lib/puma/server.rb:395 :in `close`
 IOError: stream closed
 [GEM_ROOT]/gems/puma-3.10.0/lib/puma/server.rb:391 :in `write`
 [GEM_ROOT]/gems/puma-3.10.0/lib/puma/server.rb:391 :in `rescue in handle_servers`
 [GEM_ROOT]/gems/puma-3.10.0/lib/puma/server.rb:400 :in `handle_servers`
 [GEM_ROOT]/gems/puma-3.10.0/lib/puma/server.rb:327 :in `block in run`
 IOError: stream closed
 [GEM_ROOT]/gems/puma-3.10.0/lib/puma/reactor.rb:210 :in `join`
 [GEM_ROOT]/gems/puma-3.10.0/lib/puma/server.rb:388 :in `handle_servers`
 [GEM_ROOT]/gems/puma-3.10.0/lib/puma/server.rb:327 :in `block in run``

**Comment by NickolasVashchenko** [comment] 2017-11-21 09:06
Please, either update to 2.4.2 or install the mentioned gem.
