### ISSUE TITLE
Windows - Process finished with exit code -1073741819

### ISSUE THREAD

**Issue by lucamezzolla** [puma/puma#2289] opened 2020-06-01 14:47 UTC
Hi,
I use Windows 10 and when I launch puma and I go in a simple view, PUMA exit with this message: "Process finished with exit code -1073741819". I can't find solutions.

**Comment by MSP-Greg** [comment] 2020-06-01 18:00
I often use puma locally to check a static site.  It seems to work fine.  Without more details, it's difficult to know what the issue is.  Maybe something with your app?  Can you check it with webrick?

**Comment by neongrau** [comment] 2020-09-04 08:25
I'm seeing the same here, happens consistently when i try to access an IO object from a cloud storage persisted file via Shrine gem.

As soon as i try to `IO.copy_stream` or just call `.rewind` puma will silently exit with above exit code.
Same code can be run without any issue from a rails console.

**Comment by neongrau** [comment] 2020-09-08 12:16
Took me a while to figure out since when i ran the rails app via thin server instead of puma i didn't get these segfaults. After looking into it via x64dbg i found it's a bug in x64-msvcrt-ruby250.dll from ruby 2.5.7p206.

Likely this https://bugs.ruby-lang.org/issues/16357 issue which was never fixed for the ruby 2.5 branch as it seems. After upgrading to ruby 2.6.6 the problem is gone.

**Comment by nateberkopec** [comment] 2020-09-08 19:52
@lucamezzolla What Ruby version were you using? Can you try 2.6+, as suggested?

**Comment by dentarg** [comment] 2021-02-06 17:10
Closing this one, we need more info to be able to take any action here. Hopefully it works with Ruby >= 2.6.

For the record, some (old) links that mention the same error code:

* https://stackoverflow.com/questions/9067196/process-finished-with-exit-code-1073741819
* https://github.com/oneclick/rubyinstaller/issues/100

**Closed by dentarg** 2021-02-06 17:10 UTC
Labels: needs-repro, windows
