### ISSUE TITLE
Puma 6  deadlock,  when a code-reload occurs,  while an actioncable connection is open 

### ISSUE THREAD

**Issue by gamecreature** [puma/puma#3010] opened 2022-11-04 07:16 UTC
A deadlock happens on a code reload when the page has open ActionCable/Websockets connection.
This only occures in development mode with Puma 6. 

More details can be found this sample project I created:  

https://github.com/gamecreature/puma6-dev-deadlock

**Puma config:**

Default puma config file from the rails distribution.

**To Reproduce**

1. startup the server
   ```bash
   rails server
   ```
2. Open the app in a browser on a page with an open actioncable stream http://localhost:3000/
3. Refresh the page (Cmd+R)
4. No problems yet.
5. Do a code change in for example `app/views/messages/index.html.erb` and save the file
6. Refresh the page (Cmd+R)
7. The app hangs, usually the first time.

**Expected behavior**
I don't expect a deadlock to occure

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Puma Version [6.0]
 - Using latest Safari to trigger the refresh

**Extra things I noticed**
 - This happens in several application that use an actioncable connection I have tested with Puma 6
 - The code runs fine with Puma 5
 - removing an active ActionCable/Websocket connection from the page will stop this bug. (I assume the deadlock occures in the combination with ActionCable/Websockets). In this code example removing the turbo_stream_from "messages" line, solves it.
 - The problem doesn't happen in production mode
 - The problem happens when a code-reload takes place
 - I also suspect this problem occures when switching hostnames within the same application (I noticed this problem in a pretty complex multi-tentant App, which hangs when going to another hostname, even without code change)

**Comment by gamecreature** [comment] 2022-11-04 07:47
Well it seams that this is issue has been resolved yesterday 3d33475dd400c8d097889ddd93fab38d080c25e0.
You guys are really fast! 😂

**Comment by dentarg** [comment] 2022-11-05 11:20
Closing as duplicate of https://github.com/puma/puma/issues/2999

**Closed by dentarg** 2022-11-05 11:20 UTC
Labels: duplicate

**Comment by andreynering** [comment] 2024-04-22 21:17
Was this really fixed? Because I've been experiencing deadlocks on code reloads on Rails for months.

**Comment by navidemad** [comment] 2024-04-23 11:24
In development environnement, same sometimes randomly a page is taking very long time to load. If i close the rails server and relaunch it, it loads again instantely.

**Comment by andreynering** [comment] 2024-04-23 13:51
@navidemad Exactly. On my case I have to run `kill -9 $(cat tmp/pids/server.pid)` on these cases because a regular `CTRL+C` isn't enough to kill the server.

I've been trying to find a solution for quite some time, but without any luck.

**Comment by Amnesthesia** [comment] 2024-09-04 00:52
I'm experiencing this 100% of the time when I run puma with a single worker (no cluster), and quite often when running puma in clustered mode but less noticable as other workers pick up the task

**Comment by humphreyja** [comment] 2024-09-10 21:47
We're also running into this running Puma 6.4.2 in development. It's very frustrating needing to restart the server basically every or every other code change.

**Comment by dentarg** [comment] 2024-09-11 05:41
Can you reproduce your problems without actioncable? If so, feel free to open a new issue. If it only happens with actioncable, I would suggest open an issue on the actioncable repo.

Please note that it is important that you can explain how to reproduce the issue.

**Comment by abuisman** [comment] 2024-10-18 07:22
I have the same issue. Whenever I change code in my rails app and do a reload, I get a very slow restart. I have websocket connections open to actioncable (for hotwire).
