### ISSUE TITLE
upstart puma-manager won't start

### ISSUE THREAD

**Issue by jogaco** [puma/puma#949] opened 2016-04-08 09:59 UTC
My system: Ubuntu 14.04.1 LTS

puma-manager will not run unless I rename it to puma_manager.conf

**Comment by evanphx** [comment] 2016-04-08 19:15
What does it do when you try to start it?

**Comment by jogaco** [comment] 2016-04-08 20:47
Seems odd but this is the behaviour.

`sudo service puma-manager start` => works fine
`sudo bootup` => does not work
whereas if I change the name to `puma_manager.conf`, both scenarios work.

And on several machines.
I was moving my app to a new machine from a different provider and thus had the chance to try and fix this with the unused one.

**Comment by evanphx** [comment] 2016-04-12 16:24
What is `bootup`?

**Comment by jogaco** [comment] 2016-04-14 20:11
I meant sudo reboot

**Comment by evanphx** [comment] 2016-04-23 00:09
@jogaco I'm still very unsure what the issue is. Can you explain further?

**Comment by jogaco** [comment] 2016-04-25 19:14
The service will not start automatically upon rebooting the system, with the current filename of `puma-manager.conf`.
However, it will start fine if the file is renamed to `puma_manager.conf`

**Comment by evanphx** [comment] 2016-07-24 04:57
Ok, so I guess keep it that name? Whats wrong with it being `puma_manager.conf`?

**Comment by evanphx** [comment] 2016-07-24 23:01
Because of the age, I'm going to go ahead and close this. If it's still an issue, please reopen.

**Closed by evanphx** 2016-07-24 23:01 UTC
