### ISSUE TITLE
Puma hangs on shutting down workers when received SIGINT

### ISSUE THREAD

**Issue by atitan** [puma/puma#1674] opened 2018-11-08 09:22 UTC
### Steps to reproduce
```
bundle exec puma -C config/puma.rb

# in another terminal
kill -SIGINT {puma pid}
```

### Expected behavior
```
[72484] Use Ctrl-C to stop
[72484] - Worker 0 (pid: 72516) booted, phase: 0
[72484] - Worker 1 (pid: 72517) booted, phase: 0
[72484] - Gracefully shutting down workers...
[72484] === puma shutdown: 2018-11-08 17:19:54 +0800 ===
[72484] - Goodbye!
```

### Actual behavior

Workers are already shut down, but the cluster master hanged on `Process.waitpid`.

However, if I press ctrl+c after puma hanged , it terminated correctly.
```
[72484] Use Ctrl-C to stop
[72484] - Worker 0 (pid: 72516) booted, phase: 0
[72484] - Worker 1 (pid: 72517) booted, phase: 0
[72484] - Gracefully shutting down workers...
```

### System configuration

**Operating System**: macOS 10.14.1
**Ruby version**: 2.5.3
**Rails version**: 5.2.1
**Puma version**: 3.12.0
**Bundle version**: 1.16.6

**Comment by ioquatix** [comment] 2018-12-08 23:47
I seem to start experiencing this with 2.6.0-rc1 on travis - maybe an odd coincidence?

https://travis-ci.com/socketry/falcon/jobs/163846367 - scroll to the end.

**Comment by dentarg** [comment] 2019-01-07 15:34
@ioquatix I think you are seeing https://bugs.ruby-lang.org/issues/15499

We see it for our app using Puma cluster mode, it does not exit on SIGTERM. On Heroku, we are getting [R12 - Exit timeout](https://devcenter.heroku.com/articles/error-codes#r12-exit-timeout) errors.

**Comment by MSP-Greg** [comment] 2019-01-07 15:39
I believe this issue may have also been causing failing tests on Travis when ruby-head was 2.6.0dev, the tests are skipped on Windows/Appveyor due to lack of `fork`...

**Comment by guilleiguaran** [comment] 2019-03-10 18:14
I think this is fixed by https://github.com/puma/puma/pull/1738 also

**Comment by evanphx** [comment] 2019-03-12 00:02
This sounds like a bug in ruby 2.6.

**Comment by ioquatix** [comment] 2019-03-12 00:12
Let me see if I can reproduce the issue in 2.6.1

**Comment by MSP-Greg** [comment] 2019-03-12 00:45
I believe this issue has been around since 2018-Aug, between r64316 and r64376.

Some travis build info:

Failed builds
2999 ruby 2.6.0dev (2018-08-15 trunk 64376) [x86_64-linux] Address in Use
2998 ruby 2.6.0dev (2018-08-15 trunk 64376) [x86_64-linux] Address in Use

Passing builds
2997 ruby 2.6.0dev (2018-08-12 trunk 64316) [x86_64-linux] Cron
2993 ruby 2.6.0dev (2018-08-07 trunk 64208) [x86_64-linux] Cron
2981 ruby 2.6.0dev (2018-07-24 trunk 64026) [x86_64-linux]

**Comment by dentarg** [comment] 2019-03-12 17:16
> This sounds like a bug in ruby 2.6.

I think so too, 2.6 changed the behaviour of our specs, that started and stopped our application using Puma in cluster mode. I've extracted the code to https://github.com/dentarg/gists/tree/master/gists/ruby-bug-15499 to reproduce the problem. [Before 2.6](https://github.com/dentarg/gists/tree/master/gists/ruby-bug-15499#253) our specs was able to stop Puma without leaving and Ruby processes behind.

I made some comments about this in https://bugs.ruby-lang.org/issues/15499 but it hasn't gone anywhere since. I've been thinking about opening a new bug, but we switched our application single mode so the issue hasn't been pressing. I can chime in if anyone here opens a new bug.

**Comment by MSP-Greg** [comment] 2019-03-12 17:22
@dentarg

Is it a bug or a breaking change?

I think #1741 seems to be working, I don't know how hard it would be for you to test it...

**Comment by dentarg** [comment] 2019-03-13 12:40
@MSP-Greg I have tested #1741, see https://github.com/dentarg/gists/tree/master/gists/ruby-bug-15499#261--httpsgithubcompumapumapull1741. Seems like it behaves as 2.5.3 does.

**Comment by MSP-Greg** [comment] 2019-03-13 13:13
@dentarg

Thanks for testing.

> Seems like it behaves as 2.5.3 does.

To clarify, that means that the PR fixes the issue you've had with Ruby 2.6/trunk?

**Comment by dentarg** [comment] 2019-03-13 14:37
Yes, I think so, at least some of it. Something I didn't do but could be done: try to reproduce the problem on Heroku (but it looks like the original post is doing something similar)

**Comment by MSP-Greg** [comment] 2019-03-13 15:03
>  try to reproduce the problem on Heroku

Maybe @schneems has seen the issue with 2.6/trunk somewhere?

**Comment by AlexWayfer** [comment] 2019-03-14 10:00
It seems that this issue is also in Ruby 2.5.4 now.

**Comment by mltsy** [comment] 2019-03-18 20:16
Not only that - puma doesn't work in clustered mode at all with this ruby update!  I'll put in another ticket for that though.

**Comment by guilleiguaran** [comment] 2019-03-18 20:23
@mltsy have you tested 2.5.5? afaik Ruby 2.5.5 was released to handle the regression in 2.5.4

**Comment by mltsy** [comment] 2019-03-18 20:44
Ah!  Indeed.  I just saw, as I was going to put in a ticket, that there was actually ticket submitted and resolved for that very reason that I had missed previously because it was already closed :)  Thanks!  And it looks like that update also resolves the issue in this ticket - although perhaps it still exists in the Ruby 2.6 branch?

**Comment by MSP-Greg** [comment] 2019-03-18 21:56
If anyone wants to try a PR that may solve the clustered issue, the following in a gemfile:

```
gem 'puma', :git => 'https://github.com/puma/puma.git', :ref => 'refs/pull/1741/head'
```

**Comment by mltsy** [comment] 2019-03-18 22:39
That does seem to allow puma to shutdown gracefully in ruby 2.5.4 with that branch. :+1:

(However, requests still don't get through in clustered mode in ruby 2.5.4 even with that branch)

**Comment by MSP-Greg** [comment] 2019-03-18 22:44
Thanks for checking.

> However, requests still don't get through in clustered mode in ruby 2.5.4

  Not good.  Any idea if 2.5.5 fixes it (or using 2.6.2)?

**Comment by mltsy** [comment] 2019-03-18 22:47
2.5.5 does fix both issues, yeah!

**Comment by MSP-Greg** [comment] 2019-03-18 22:49
Good.  Is that using standard 3.12.0 or the git version with PR 1741?

**Comment by mltsy** [comment] 2019-03-18 22:52
Yeah, ruby 2.5.5 fixes it even with standard 3.12.0 puma branch 😄 

(And I'm not sure about ruby 2.6 - I can't seem to reproduce the problem with 2.6, and am not sure which version it exists in exactly)

**Comment by MSP-Greg** [comment] 2019-03-18 22:56
Thanks again.

> Yeah, ruby 2.5.5 fixes it even with standard 3.12.0 puma branch

I don't recall any issues with Ruby 2.5.x < 2.5.4, it was only 2.5.4 that broke.

Ruby trunk started failing on clustered shutdown/restart last year some time, so the patch was for compatibility with Ruby 2.6 and current trunk (2.7.0).

**Comment by mltsy** [comment] 2019-03-18 23:06
Interesting... well when I ran it with Ruby 2.6.2, everything worked fine for me (with the standard 3.12.0 puma branch - did they fix it in 2.6.2?)

**Comment by MSP-Greg** [comment] 2019-03-18 23:16
PR #1747 updated the Travis matrix from 2.6.1 to 2.6.2, and it & trunk seem to be failing (2.5.5 is ok):

https://travis-ci.org/puma/puma/builds/507190071

**Comment by mltsy** [comment] 2019-03-18 23:38
Huh... I setup a docker-compose stack with ruby 2.6.2-p47 and puma 3.12.0 in clustered mode (`-w 2` flag) and it exits fine in every way I've tested it... that's odd.  I must not be hitting exactly the right test case?

**Comment by guilleiguaran** [comment] 2019-03-19 13:59
@atitan can you test with master and confirm if this can be closed?

**Comment by atitan** [comment] 2019-03-20 02:39
@guilleiguaran I've tested against master@27a09c4, but it behaves like I wrote in the original issue.

Environment:
 - OS version: macOS 10.14.3
 - Ruby version: 2.6.2
 - Rails version 5.2.2.1
 - Bundler version 2.0.1

Behavior:
```
$ bundle exec puma -C config/puma.rb
[95865] Puma starting in cluster mode...
[95865] * Version 3.12.1 (ruby 2.6.2-p47), codename: Llamas in Pajamas
[95865] * Min threads: 5, max threads: 5
[95865] * Environment: development
[95865] * Process workers: 2
[95865] * Preloading application
[95865] * Listening on tcp://0.0.0.0:3000
[95865] Use Ctrl-C to stop
[95865] - Worker 0 (pid: 95907) booted, phase: 0
[95865] - Worker 1 (pid: 95908) booted, phase: 0

# Send SIGINT here
[95865] - Gracefully shutting down workers...
[95865]     worker status: pid 95907 exit 0
[95865]     worker status: pid 95908 exit 0
[95865]     worker shutdown time:   0.50
# Puma stuck here with worker already shutdown

# Have to press ctrl-c to shut it down, sending signal again does not help
^C[95865] === puma shutdown: 2019-03-20 10:32:19 +0800 ===
[95865] - Goodbye!
```

**Comment by atitan** [comment] 2019-03-20 03:00
I tried packing my application in Docker. It seems the patch works on Linux platform(previously not).

```
$ docker run --env-file=.env ee1cc795c928 bundle exec puma -C config/puma.rb
[6] Puma starting in cluster mode...
[6] * Version 3.12.1 (ruby 2.6.2-p47), codename: Llamas in Pajamas
[6] * Min threads: 5, max threads: 5
[6] * Environment: production
[6] * Process workers: 2
[6] * Preloading application
I, [2019-03-20T02:55:34.471560 #6]  INFO -- : Raven 2.9.0 ready to catch errors
[6] * Listening on tcp://0.0.0.0:3000
[6] ! WARNING: Detected 1 Thread(s) started in app boot:
[6] ! #<Thread:0x00007f536ca5ec38@/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:299 sleep> - /usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:301:in `sleep'
[6] Use Ctrl-C to stop
[6] - Worker 0 (pid: 17) booted, phase: 0
[6] - Worker 1 (pid: 30) booted, phase: 0

# Received signal here
[6] - Gracefully shutting down workers...
[6]     worker status: pid 17 exit 0
[6]     worker status: pid 30 exit 0
[6]     worker shutdown time:   0.50
[6] === puma shutdown: 2019-03-20 02:56:55 +0000 ===
[6] - Goodbye!
```

```
# in another terminal
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
3d6d3b768a0b        ee1cc795c928        "/usr/bin/dumb-init …"   25 seconds ago      Up 24 seconds                           priceless_poincare
$ docker kill -s SIGINT 3d6d3b768a0b
3d6d3b768a0b
```

**Comment by guilleiguaran** [comment] 2019-03-20 03:06
@atitan you're right, the fix seems to work on Linux but fails on macOS, I just confirmed it in a machine with macOS.

/cc @MSP-Greg

**Comment by evanphx** [comment] 2019-03-20 03:24
@guilleiguaran Can you give me more info about your macOS setup? I can't replicate the issue here.

**Comment by evanphx** [comment] 2019-03-20 03:26
@atitan I need to get more information about your setup. Can you provide your config.rb and any info about your rails app?

**Comment by atitan** [comment] 2019-03-20 03:56
@evanphx 
I just created a new rails app to test with. Found out adding `preload_app!` in puma config hanged the cluster master.

Besides, if I don't preload the app, ActiveSupport constant will not be defined in `on_worker_boot` block.

My config looks like this
```
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
threads threads_count, threads_count

port        ENV.fetch("PORT") { 3000 }
environment ENV.fetch("RAILS_ENV") { "development" }
workers ENV.fetch("WEB_CONCURRENCY") { 2 }
preload_app!

before_fork do
  if defined?(ActiveRecord::Base)
    ActiveRecord::Base.connection_pool.disconnect!
  end
end
on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
plugin :tmp_restart
persistent_timeout 620
```

**Comment by evanphx** [comment] 2019-03-20 04:11
@atitan Sorry, still unable to reproduce it with an empty rails app. Can you send your Gemfile?

**Comment by atitan** [comment] 2019-03-20 04:28
@evanphx 

Here you are.
I noticed a strange situation that puma does not hang if I started it in production mode.

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.2'

gem 'rails', '~> 5.2.2', '>= 5.2.2.1'
gem 'sqlite3', '~> 1.3.6'
gem 'puma', '~> 3.11', github: 'puma/puma', branch: 'master'

gem 'bootsnap', '>= 1.1.0', require: false

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
end
```

**Comment by evanphx** [comment] 2019-03-20 04:38
Still unable to repro. Maybe can you push the rails app up to github and I can try it exactly as you have it?

**Comment by evanphx** [comment] 2019-03-20 04:39
Here is what mine looks like:

```
~/tmp/puma-test master* 9s
❯ bundle exec puma -C config/puma.rb
[38384] Puma starting in cluster mode...
[38384] * Version 3.12.1 (ruby 2.6.2-p47), codename: Llamas in Pajamas
[38384] * Min threads: 5, max threads: 5
[38384] * Environment: development
[38384] * Process workers: 2
[38384] * Preloading application
[38384] * Listening on tcp://0.0.0.0:3000
[38384] ! WARNING: Detected 4 Thread(s) started in app boot:
[38384] ! #<Thread:0x00007fb93049b7e0@/Users/evan/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 sleep> - /Users/evan/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rb-fsevent-0.10.3/lib/rb-fsevent/fsevent.rb:44:in `select'
[38384] ! #<Thread:0x00007fb93049b380@/Users/evan/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 sleep> - /Users/evan/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/event/config.rb:19:in `sleep'
[38384] ! #<Thread:0x00007fb93032faf0@/Users/evan/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 sleep> - /Users/evan/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/record/entry.rb:42:in `realpath'
[38384] ! #<Thread:0x00007fb93032f848@/Users/evan/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 sleep> - /Users/evan/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/event/config.rb:19:in `sleep'
[38384] Use Ctrl-C to stop
[38384] - Worker 0 (pid: 38395) booted, phase: 0
[38384] - Worker 1 (pid: 38396) booted, phase: 0
^C[38384] - Gracefully shutting down workers...
[38384]     worker status: pid 38395 exit 0
[38384]     worker status: pid 38396 exit 0
[38384]     worker shutdown time:   0.51
[38384] === puma shutdown: 2019-03-19 21:37:58 -0700 ===
[38384] - Goodbye!
```

**Comment by atitan** [comment] 2019-03-20 05:46
@evanphx 
The key point here is `don't use ctrl-c`.
Use `kill` to send SIGINT to the process.
The Ctrl-C will always work even it hanged.

**Comment by atitan** [comment] 2019-03-20 06:35
To sum up, reproducing the issue requires:
 - macOS
 - puma in development and cluster mode
 - preload_app!
 - use kill to send signal instead of ctrl-c

**Comment by guilleiguaran** [comment] 2019-03-20 07:12
I can reproduce in a new rails app using the same configuration that @atitan described but I'm not able to reproduce under test conditions or using a bare rack app:

```ruby
# config.ru
run lambda { |env| [200, {'Content-Type'=>'text/plain'}, ["Hello Rack!"]] }
```

```ruby
# puma_config.rb
threads 4, 4
workers 2
environment "development"
preload_app!
```

```ruby
# Gemfile
source 'https://rubygems.org'

gem 'puma', github: 'puma/puma'
gem 'rack'
```

**Comment by greggilbert** [comment] 2019-05-30 04:07
This issue hasn't been touched in awhile, but I'm seeing the same issue (or very similar). 

Context:
* Docker container, Debian 9.9 (stretch)
* Ruby 2.6.3p62
* Puma 3.12.1
* Hanami 1.3.1

I'm invoking Puma using `puma -C puma.rb`. The process is being controlled via s6.

```
# puma.rb
bind 'tcp://127.0.0.1:9292'
workers 3

preload_app!
```

What I'm seeing now is that, if i do `kill -SIGINT` (or have my process manager send a `SIGINT`), then Puma shuts down gracefully. `kill -SIGTERM`, however, causes the shutdown to freeze, and I get a bunch of `[ruby] <defunct>` threads.

It seems like using `SIGINT` is a workaround for using `SIGTERM`, but I'm wondering if that will have any adverse effects on things. 

Anyway, hopefully this helps. Happy to try out any potential fixes if need be.

**Comment by dentarg** [comment] 2019-05-30 08:28
@greggilbert do you mind trying your repro with Puma from the master branch? related PR https://github.com/puma/puma/pull/1741 has been merged but not released yet

**Comment by greggilbert** [comment] 2019-05-30 12:08
I updated my Gemfile:
```gem 'puma', github: 'puma/puma', branch: 'master'```

```
$ bundle list puma
/usr/local/bundle/bundler/gems/puma-d39fe92a2dd1
```

I ran `bundle exec puma -C puma.rb` and then brought up the process. In a separate terminal, `kill -TERM $PID` did, in fact, kill the process. 

This is interesting, though: when I rebuilt my Docker container, during the `bundle install` step, it threw this warning:

```Using puma 3.12.1 from git://github.com/puma/puma.git (at master@d39fe92)
/usr/local/lib/ruby/2.6.0/rubygems/ext/builder.rb:183: warning: conflicting chdir during another chdir block
/usr/local/lib/ruby/2.6.0/rubygems/ext/builder.rb:191: warning: conflicting chdir during another chdir block
```

And then when trying to run `puma -C puma.rb`, it threw this fatal error:
```puma -C puma.rb
Traceback (most recent call last):
	2: from /usr/local/bundle/bin/puma:23:in `<main>'
	1: from /usr/local/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/usr/local/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem puma (>= 0.a) with executable puma (Gem::GemNotFoundException)
```

Running `bundle exec puma -C puma.rb` worked fine, though. Is that the correct way to run Puma in this case?

**Comment by nateberkopec** [comment] 2019-05-30 13:56
Nice, can anyone see if https://github.com/puma/puma/issues/1674#issuecomment-474704874 still reproduces?

**Comment by hrparty** [comment] 2019-06-12 11:08
> Nice, can anyone see if [#1674 (comment)](https://github.com/puma/puma/issues/1674#issuecomment-474704874) still reproduces?

I've had this problem for months (since updating to ruby 2.6) on my machine, running under the conditions in https://github.com/puma/puma/issues/1674#issuecomment-474704874. 

3.12.1 does not fix the problem for me but I'm running my rails app on master now (with this in my gemfile: `gem 'puma', github: 'puma/puma'`) and I don't see this anymore. I believe it got fixed in this commit https://github.com/puma/puma/commit/c637ff0d07a8f20040cabc9b4bb758a2a931edce, because I started running on master with good results just after that was committed.

**Comment by nateberkopec** [comment] 2019-06-12 18:02
Closing as fixed on master b/c I agree. 

This will be in the next release after 3.12.1.

**Closed by nateberkopec** 2019-06-12 18:02 UTC
Labels: bug

**Comment by AlexWayfer** [comment] 2019-06-13 11:18
> This will be in the next release after 3.12.1.

Do you have plans for date of next release?

Because the current stable version of `puma` is incompatible with the current stable version of Ruby (`2.6`).

**Comment by nateberkopec** [comment] 2019-06-13 18:29
Maintainers are meeting tomorrow, I would expect a release Soon (TM).

**Comment by morgler** [comment] 2021-05-04 16:28
I have a similar problem with puma 5.2.2 and ruby 2.7.1. Starting rails (6.0.3.6) with `bundle exec rails s` starts puma. Trying to shut down the server with `Ctrl-C` leaves puma hanging with the message `Gracefully shutting down workers...`. 

I tried with one worker and with two workers – same problem. What can I do to fix this?

**Comment by nateberkopec** [comment] 2021-05-04 16:42
@morgler please start a new issue
