### ISSUE TITLE
Starting rails server with a different port

### ISSUE THREAD

**Issue by khpatel4991** [puma/puma#1200] opened 2017-01-30 03:54 UTC
### Steps to reproduce

1) I have a simple rails 5 API app, and I updated puma to 3.7.0. I start my server on port 3090 with `rails server -p 3090` as I have frontend app running on 3000.

### Expected behavior
It should start listening on port 3090, not on the default 3000.
### System configuration

**Ruby version**: RVM 2.3.3-p222
**Rails version**: 5.0.1

Logs:
```
rs -p 3090
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:3090
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.7.0 (ruby 2.3.3-p222), codename: Snowy Sagebrush
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Exiting
~/.rvm/gems/ruby-2.3.3/gems/puma-3.7.0/lib/puma/binder.rb:269:in `initialize': Address already in use - bind(2) for "0.0.0.0" port 3000 (Errno::EADDRINUSE)
```

**Comment by twalpole** [comment] 2017-01-30 05:37
This is basically the same as issue #1199

**Comment by richpeck** [comment] 2017-01-30 15:21
+1

**Comment by michael-reeves** [comment] 2017-01-30 20:52
Seeing the same thing trying to run port 3001.

**Comment by ayghor** [comment] 2017-01-31 03:03
see https://github.com/puma/puma/commit/42bec4600c51ab8a1c1ee5a0e1b738a4ffd82bf2, it was tagged `v3.6.2` and was __NOT__ merged on `v3.7.0` for some reason:

>     Revert "fix access priorities of each level in LeveledOptions"
>     
>     This reverts commit 15f0847289d0815284f87eeea4625100b581c026.
>     
>     See #1154, this commit unintentionally changed behavior regarding the
>     importance of command line options.

cant test reverting teh reversion right now

**Comment by ayghor** [comment] 2017-01-31 03:04
`v3.2.6` respect `-p` switch, `v3.7.0` does not.

**Comment by andrew** [comment] 2017-01-31 09:33
A similar thing happened back in November: https://github.com/puma/puma/issues/1154

**Comment by ivanovaleksey** [comment] 2017-02-07 14:37
@ayghor Do you mean `3.6.2`? Since `3.2.6' [doesn't exist](https://rubygems.org/gems/puma/versions).
And with `3.6.2` it works fine.

**Comment by ayghor** [comment] 2017-02-07 14:38
> @ayghor Do you mean 3.6.2? Since 3.2.6 doesn't exist.
> And with 3.6.2 it works fine.

yes, `3.6.2`

**Comment by roeintense** [comment] 2017-02-08 04:13
Same problem. Downgraded to 3.6.2, everything fat and sassy again.

**Comment by jaswinder97** [comment] 2017-02-09 10:39
After updating the gem version and bundling: 

gem 'puma', '~> 3.6.2'

if problem still persists,then try to kill the running puma process first:

 ps aux | grep puma

2598  2.4  3.5 1017520 141400 pts/16 Sl+  15:57   0:04 puma 3.7.0 (tcp://0.0.0.0:3000) [rails-app]

and then restart the app again 

jaswind+  2950 11.0  3.6 1020164 143996 pts/10 Sl+  16:02   0:04 puma 3.6.2 (tcp://0.0.0.0:3000) [rails_app_copy]                                                                                              
jaswind+  2976 18.1  3.6 1020880 144788 pts/16 Sl+  16:02   0:04 puma 3.6.2 (tcp://0.0.0.0:3001) [rails_app]

**Comment by nateberkopec** [comment] 2017-02-09 14:07
Yeah @ayghor got it right, for some reason I reverted on the 3.6.2 branch but never on master. My very, very bad. Fixed by above.

**Closed** 2017-02-09 14:07 UTC

**Comment by nateberkopec** [comment] 2017-02-09 14:08
Gonna push out 3.7.1 with this fix ASAP.

**Comment by remi** [comment] 2017-02-16 23:00
Is there an ETA for 3.7.1 going out with this fix?

**Comment by nateberkopec** [comment] 2017-02-18 00:00
@remi Yes, sorry! had to have a meeting with Evan last week to discuss how the release process works, working on a 3.7.1 now.

**Comment by martinobettucci** [comment] 2017-05-04 08:59
This bug is back into 3.8.2, so there was regression.
I fixed going back to 3.6.2

**Comment by martinobettucci** [comment] 2017-05-04 09:07
Updated comment

**Comment by TechGiovanni** [comment] 2022-11-26 03:53
you can try this piece of code. In your terminal copy and paste below, Rails will run on port 4000, by adding the Port variable before the number as -p doesn't work sometimes.

PORT=4000 rails server
