### ISSUE TITLE
Updating to Puma 3.7.0 breaks teaspoon integration

### ISSUE THREAD

**Issue by angeleah** [puma/puma#1204] opened 2017-01-31 17:06 UTC
### Steps to reproduce

1) update to puma 3.7.0

2) $rake teaspoon

### Expected behavior
Starting the Teaspoon server...
Puma starting in single mode...
* Version 3.6.2 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: test
* Listening on tcp://127.0.0.1:49819
Use Ctrl-C to stop
Teaspoon running default suite at http://127.0.0.1:49819/teaspoon/default
Finished in 1.07500 seconds
68 examples, 0 failures, 0 pending

Usually runs as normal

### Actual behavior
rake teaspoon
Starting the Teaspoon server...
Puma starting in single mode...
* Version 3.7.0 (ruby 2.3.3-p222), codename: Snowy Sagebrush
* Min threads: 5, max threads: 5
* Environment: test
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Unable to start teaspoon server; consider increasing the timeout with `config.server_timeout`.

bundle exec teaspoon returned exit code 1

### System configuration

**Ruby version**: 2.3.3
**Rails version**: 5.0.1

**Comment by wrburgess** [comment] 2017-01-31 22:17
Temporary solution posted here: https://github.com/teamcapybara/capybara/issues/1831

**Comment by twalpole** [comment] 2017-02-02 07:03
This is caused by the same problem as issue #1199 #1200 and #1201

**Comment by angeleah** [comment] 2017-02-02 16:15
I suspected so but thought it would still be good to get it documented. Thank you!

**Comment by nateberkopec** [comment] 2017-02-09 14:09
Closed by #1200

**Closed by nateberkopec** 2017-02-09 14:09 UTC
