### ISSUE TITLE
How can I fix "WARNING: Detected 2 Thread(s) started in app boot:" with concurrent-ruby?

### ISSUE THREAD

**Issue by ndbroadbent** [puma/puma#2237] opened 2020-04-27 13:32 UTC
* Puma: 4.3.3
* Rails: 5.2.4.2
* Ruby: 2.6.5

I've been trying to get rid of this in my logs `WARNING: Detected 2 Thread(s) started in app boot:`.

Here are the logs when I start puma:

([I edited this line to print the full backtrace](https://github.com/puma/puma/blob/67f9b1f3f2318c14279ba212ebdfaa5bccd9bc08/lib/puma/cluster.rb#L421).)

```
[69210] ! WARNING: Detected 2 Thread(s) started in app boot:
[69210] ! #<Thread:0x00007ffa9f28e500@/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:41 sleep_forever> - /Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:43:in `pop'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:43:in `block in <class:RubyThreadLocalVar>'
[69210] ! #<Thread:0x00007ffab82b49a8@/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:303 sleep> - /Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:305:in `sleep'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:305:in `block (2 levels) in run'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:304:in `loop'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:304:in `block in run'
```

I edited this file: `/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb`:

```
    ...
    QUEUE  = Queue.new
    puts "Ruby thread caller"
    puts "------------------------------------------------------------------"
    puts caller
    THREAD = Thread.new do
    ...
```

Output:

```
[69210] * Preloading application
Loading Rails application...
Ruby thread caller
------------------------------------------------------------------
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:8:in `<module:Concurrent>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:4:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/thread_local_var.rb:2:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/thread_local_var.rb:2:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/reentrant_read_write_lock.rb:5:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/reentrant_read_write_lock.rb:5:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomics.rb:8:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomics.rb:8:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent.rb:6:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent.rb:6:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/logger_silence.rb:5:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/logger_silence.rb:5:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/logger.rb:3:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/logger.rb:3:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support.rb:29:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support.rb:29:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails.rb:7:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails.rb:7:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/all.rb:3:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/all.rb:3:in `<top (required)>'
/Users/myuser/code/myapp/config/application.rb:7:in `require'
/Users/myuser/code/myapp/config/application.rb:7:in `<top (required)>'
/Users/myuser/code/myapp/config/environment.rb:4:in `require_relative'
/Users/myuser/code/myapp/config/environment.rb:4:in `<top (required)>'
config.ru:5:in `require_relative'
config.ru:5:in `block in <main>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/configuration.rb:321:in `load_rackup'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/configuration.rb:246:in `app'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/runner.rb:155:in `load_and_bind'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/cluster.rb:413:in `run'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/launcher.rb:172:in `run'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/cli.rb:80:in `run'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/bin/puma:10:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/bin/puma:23:in `load'
/Users/myuser/.rbenv/versions/2.6.5/bin/puma:23:in `<main>'
```

`/Users/myuser/code/myapp/config/application.rb:7` is just:

```
require 'rails/all'
```

~The problem seems to be that bootsnap requires `concurrent-ruby` when the app boots~ (UPDATE: I was getting a lot of bootsnap lines in the backtrace so I turned it off, but the warning is still happening.)

`lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb` is required, and this creates a new Thread immediately when the class is loaded:

```
module Concurrent
  class RubyThreadLocalVar < AbstractThreadLocalVar
    FREE   = []
    LOCK   = Mutex.new
    ARRAYS = {} # used as a hash set
    @@next = 0
    QUEUE  = Queue.new
    THREAD = Thread.new do
      while true
      ...
```

(`Thread.new` is called while the class is being defined, and not inside a method.)

Does that mean that this `RubyThreadLocalVar` thread is not working properly inside the puma workers? I haven't noticed any problems with my app in production, but now I'm concerned that something isn't working properly.

Thanks for your time!

**Comment by ndbroadbent** [comment] 2020-04-27 13:53
I've also opened an issue on concurrent-ruby: https://github.com/ruby-concurrency/concurrent-ruby/issues/868, to see if they have any thoughts

**Comment by dentarg** [comment] 2020-04-27 14:30
I think you need to show your Puma config and maybe also code the full code to reproduce to, for someone to be able to advise you properly.

**Comment by nateberkopec** [comment] 2020-04-27 23:21
I'm interested to hear what the concurrent-ruby people think. If they weren't creating threads at require-time, this wouldn't be an issue.

**Comment by dwishrq** [comment] 2020-07-23 09:10
As a possible (temporary?) workaround, I noticed that I get this warning on startup using v1.1.6 of concurrent-ruby (as the original post above also did) but when I downgraded to 1.1.5 the warning went away.

**Comment by andrewhavens** [comment] 2020-07-23 22:39
I'm getting the same warning with the same gem versions. My app is also running on Heroku. I wonder if there are any problems with my current Puma config:

```ruby
require 'fileutils'
require 'barnes'

threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
threads threads_count, threads_count
port ENV.fetch("PORT") { 3000 }
environment ENV.fetch("RAILS_ENV") { "development" }

if ENV.fetch("RAILS_ENV") { "development" } == 'development'
  worker_timeout 3600
end

workers ENV.fetch("WEB_CONCURRENCY") { 4 }

preload_app!

before_fork do
  FileUtils.touch('/tmp/app-initialized')
  ActiveRecord::Base.connection_pool.disconnect! if defined?(ActiveRecord)
  Barnes.start
end

on_worker_boot do
  ActiveRecord::Base.establish_connection if defined?(ActiveRecord)
end

plugin :tmp_restart
```

**Comment by samholst** [comment] 2020-07-28 03:56
I get the same errors for `concurrent` and `activerecord` but in Rails 6 and using Ruby 2.7.0.

**Comment by nateberkopec** [comment] 2020-07-31 01:43
Looks like this will be fixed in the next version of concurrent-ruby: https://github.com/ruby-concurrency/concurrent-ruby/issues/868

**Comment by dentarg** [comment] 2020-08-08 21:29
> Looks like this will be fixed in the next version of concurrent-ruby: [ruby-concurrency/concurrent-ruby#868](https://github.com/ruby-concurrency/concurrent-ruby/issues/868)

Which has been released now: https://github.com/ruby-concurrency/concurrent-ruby/blob/v1.1.7/CHANGELOG.md#release-v117-6-august-2020, https://rubygems.org/gems/concurrent-ruby/versions

I can confirm that the new concurrent-ruby version got rid of the warning where I saw it.

**Closed** 2020-08-10 01:05 UTC
Labels: question

**Comment by h0jeZvgoxFepBQ2C** [comment] 2020-09-08 19:52
I'm still seeing this with Ruby 2.6.6 and Rails 5.2.4.3:

```
● puma_app-admin.service - Puma HTTP Server
   Loaded: loaded (/etc/systemd/system/puma_app-admin.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-09-08 21:26:14 CEST; 23min ago
  Process: 31911 ExecReload=/home/user/.rbenv/bin/rbenv exec bundle exec --keep-file-descriptors
pumactl -F /home/user/apps/app-admin/shared/puma.rb restart (code=exited, status=0/SUCCESS)
 Main PID: 25736 (ruby)
    Tasks: 26
   Memory: 399.2M
      CPU: 2min 2.902s
   CGroup: /system.slice/puma_app-admin.service
           ├─25736 puma 4.3.5 (unix:///home/user/apps/app-admin/shared/sockets/puma.app-admin
.sock?backlog=8000) [20200908194103]
           ├─32431 puma: cluster worker 0: 25736 [20200908194103]

           └─32443 puma: cluster worker 1: 25736 [20200908194103]


Sep 08 21:26:15 appake20 rbenv[25736]: [25736] * Environment: production
Sep 08 21:26:15 appake20 rbenv[25736]: [25736] * Process workers: 2
Sep 08 21:26:15 appake20 rbenv[25736]: [25736] * Preloading application
Sep 08 21:26:22 appake20 rbenv[25736]: [DEPRECATION] requiring "RMagick" is deprecated. Use "rmagic
k" instead
Sep 08 21:26:49 appake20 rbenv[25736]: [25736] * Activated unix:///home/user/apps/app-admin/s
hared/sockets/puma.app-admin.sock?backlog=8000
Sep 08 21:26:49 appake20 rbenv[25736]: [25736] ! WARNING: Detected 1 Thread(s) started in app boot:
Sep 08 21:26:49 appake20 rbenv[25736]: [25736] ! #<Thread:0x000000000a6b71c8@/home/user/apps/fl
ave-admin/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/ab
stract/connection_pool.rb:299 sleep> - /home/user/apps/app-admin/shared/bundle/ruby/2.6.0/gems/
activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:301:in `sleep'

```

Even though I have concurrent-ruby 1.1.7 in my Gemfile.lock?

**Comment by dentarg** [comment] 2020-09-09 07:46
@h0jeZvgoxFepBQ2C That's coming from activerecord: https://github.com/rails/rails/blob/v5.2.4.3/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L301

...and I can see that you've found the related issues (https://github.com/rails/rails/issues/37066, https://github.com/rails/rails/issues/25259) on rails/rails :) I guess you could try open a new issue there, or maybe better, search/ask in their forum: https://discuss.rubyonrails.org/
