### ISSUE TITLE
Puma Server hangs on restart

### ISSUE THREAD

**Issue by larryzhao** [puma/puma#1423] opened 2017-09-29 11:02 UTC
### Steps to reproduce

Don't know how to exactly reproduce. It occurs on our production servers but not every time.

After deploy, we will issuse `bundle exec pumactl -S pids/puma.state -F config/puma.rb restart` (on Ubuntu 14.04 and Ubuntu 16.04). But from time to time, we encounter that one of the puma servers hangs at restarting for very very long time, that we could only `kill -9` and start it again. There's no certain pattern of when/which it will stuck.

Like following, after 15 minutes the restart command is issued, I still sees:
```
$ ps -ef | grep puma
deployer  2535  6533 99 10:11 ?        08:33:16 puma: cluster worker 3: 6533 
deployer  2910  6533 99 10:14 ?        08:31:22 puma: cluster worker 2: 6533 
deployer  6533     1  0 01:08 ?        00:00:23 puma 3.8.2 (tcp://0.0.0.0:2801) 
deployer  9973  9683  0 18:47 pts/0    00:00:00 grep --color=auto puma
```

And if I run `strace -p 6533 -q -f` to attach and check inside puma process, I get this: https://gist.github.com/larryzhao/446234a3af91bec917119494f9bc2384

Just don't know where to look into.

### Expected behavior

Puma server should restart as normal

### Actual behavior

Puma server hangs for like forever to restart.

### System configuration

**Ruby version**: ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
**Rails version**: 5.0.5
**Puma version**: 3.8.2

**Comment by nateberkopec** [comment] 2017-10-03 14:27
Please upgrade to Puma 3.10. There have been a number of bugfixes since 3.8.2. 

You may also be experiencing [this known bug](https://github.com/puma/puma#known-bugs).

Closing for now, please re-open if you have any additional information that could lead to a reproduction, otherwise this is the best I can do.

**Comment by larryzhao** [comment] 2017-10-12 07:09
@nateberkopec I've upgraded to 3.10.0，just now i try restart puma server and the hang occurs again.

Here's something from strace the cluster process:

```
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(15, "!", 1)                       = 1
sched_yield()                           = 0
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5731, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5733, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5735, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5737, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5739, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5741, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
sched_yield()                           = 0
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5743, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5745, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5747, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5749, NULL) = 0
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(15, "!", 1)                       = 1
sched_yield()                           = 0
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5751, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5753, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
futex(0xd7f0f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5755, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f12c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0xd7f128, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xd7f0f4, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0xd7f0f0, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 1
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5759, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0xd7f0f4, FUTEX_WAIT_PRIVATE, 5761, NULL) = 0
futex(0xd7f0c0, FUTEX_WAKE_PRIVATE, 1)  = 0
write(15, "!", 1)                       = 1
wait4(-1, 0x7ffccf316220, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=31443, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(15, "!", 1)                       = 1
wait4(-1,
```

**Comment by larryzhao** [comment] 2017-10-12 09:53
Here you could see that what child process & master process is doing with strace:

```
$ ps -ef | grep puma
deployer  6149  6071  0 17:45 pts/0    00:00:00 grep --color=auto puma
deployer 18807     1  0 14:20 ?        00:00:05 puma 3.10.0 (tcp://0.0.0.0:2801)
deployer 28828 18807 54 16:12 ?        00:50:08 puma: cluster worker 4: 18807
deployer 29601 18807 71 16:21 ?        00:59:45 puma: cluster worker 3: 18807
deployer 30936 18807 80 16:38 ?        00:53:12 puma: cluster worker 6: 18807
$ sudo strace -p 30936
Process 30936 attached
futex(0x1c1081c, FUTEX_WAIT_PRIVATE, 15, NULL^CProcess 30936 detached
 <detached ...>
$ sudo strace -p 29601
Process 29601 attached
futex(0x1c1081c, FUTEX_WAIT_PRIVATE, 13, NULL^CProcess 29601 detached
 <detached ...>
$ sudo strace -p 28828
Process 28828 attached
futex(0x1c1081c, FUTEX_WAIT_PRIVATE, 29, NULL^CProcess 28828 detached
 <detached ...>
$ sudo strace -p 18807
Process 18807 attached
wait4(-1, 0x7ffeb64075e0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=18807, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(16, "!", 1)                       = 1
wait4(-1, 0x7ffeb64075e0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=18807, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0x1c100f4, FUTEX_WAIT_PRIVATE, 489, NULL) = 0
futex(0x1c100c0, FUTEX_WAKE_PRIVATE, 1) = 0
write(16, "!", 1)                       = 1
wait4(-1, 0x7ffeb64075e0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=18807, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0x1c100f4, FUTEX_WAIT_PRIVATE, 491, NULL) = 0
futex(0x1c100c0, FUTEX_WAKE_PRIVATE, 1) = 0
write(16, "!", 1)                       = 1
wait4(-1, 0x7ffeb64075e0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=18807, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0x1c100c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1c100f0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1c100f4, FUTEX_WAIT_PRIVATE, 493, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1c100c0, FUTEX_WAKE_PRIVATE, 1) = 0
write(16, "!", 1)                       = 1
wait4(-1, 0x7ffeb64075e0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TKILL, si_pid=18807, si_uid=1001} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
write(6, "!", 1)                        = 1
futex(0x1c100c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1c100f0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1c100f4, FUTEX_WAIT_PRIVATE, 495, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1c100c0, FUTEX_WAKE_PRIVATE, 1) = 0
write(16, "!", 1)                       = 1
wait4(-1, ^CProcess 18807 detached
 <detached ...>
```

Ruby: 2.3.4
Puma: 3.10.0
Rails: 5.0.5

**Comment by poc7667** [comment] 2017-12-27 16:26
Any alternative solution? Or if you gave up Puma then which server do you use now?

**Comment by larryzhao** [comment] 2017-12-27 17:46
@poc7667 no, we are still using puma. I didn't find out the exact problem or have a solution. 

But it seems that it's related to resource cleaning up. Like, if you have a slow query which causing a db connection won't end up, it may occur. I think...

So after some tuning up, it's getting better.

**Closed** 2019-09-13 16:30 UTC
Labels: needs-repro
