### ISSUE TITLE
undefined method `string' for #<Tempfile:/tmp/puma20190731-16-1uza3m1>

### ISSUE THREAD

**Issue by c2ofh** [puma/puma#1874] opened 2019-07-31 08:57 UTC
We're receiving a lot of xml messages from a webhook.
Then we parse the body to handle that message.

```ruby
@xml = Hash.from_xml(request.body.string)
```

### Expected behavior

For 99% of the request this is working fine.

### Actual behavior

Sometimes this method returns a message like this:
```
NoMethodError (undefined method `string' for #<Tempfile:/tmp/puma20190731-16-1uza3m1>):
```
It is a problem server problem or an issue for the sender?

### System configuration

**Ruby version**: 2.5.5
**Rails version**: 5.2.3
**Puma version**: 3.12.1

**Comment by nateberkopec** [comment] 2019-07-31 14:20
I don't have time to look into this right this second, but I'll give you a hint and maybe you can figure it out. Puma uses Tempfiles when the request.body is larger than a particular size.

The issue here is that the interface provided by request.body normally is *different* when it's a Tempfile. There's definitely a way we could fix that.

**Comment by Jesus** [comment] 2019-07-31 14:56
I don't think this is a bug in Puma because afaik it's not guaranteed that the body will respond to the method `#string`.

I'm assuming `request.body` in your code refers to `env['rack.input']` in Rack. If that's the case the value may be a `StringIO`, `NullIO`, `Tempfile`, ... depending on different factors. While a `StringIO` object responds to `#string`, a `Tempfile` object doesn't.

I think you'll be safer using `#read` instead of `#string`, but I'd need to know more about the context of the code you've provided to be sure.

---

I think this can be closed as what's being described is expected behaviour.

**Comment by Jesus** [comment] 2019-07-31 15:03
Also the following is useful here. Here's what Rack expects Puma to put in `env['rack.input']`: https://www.rubydoc.info/github/rack/rack/file/SPEC#label-The+Input+Stream

**Comment by nateberkopec** [comment] 2019-07-31 15:20
Good point! Forgot that's defined by the rack spec, Evan is always harping on that....

**Closed** 2019-07-31 15:19 UTC
Labels: bug
