### ISSUE TITLE
Puma >= 6.1.0 + Rails 7 produce empty rack.input in custom middleware

### ISSUE THREAD

**Issue by sanzstez** [puma/puma#3145] opened 2023-05-10 10:24 UTC
I am using custom middleware for parsing multipart/related body content. Request sending with `Transfer-Encoding: chunked`.
Everything works fine with version of puma <= 6.0.2.
But after upgrade puma to 6.1.0 rails become generate **Bad request content body** in output. And as I see with debug **env['rack.input']** contain empty string.

UPD:
During my research I found that functionality was broken by this PR: https://github.com/puma/puma/pull/3062
by adding 
```
@io.read_nonblock(4096, @read_buffer)
```
instead of
```
@io.read_nonblock(4096)
```

**Puma config:**
Default rails DEVELOPMENT config.

**To Reproduce**
Simplified middleware what I am using:

```ruby
module BlockPackage
  class Middleware
    def initialize(app)
      @app = app
    end

    def call(env)
      if env['CONTENT_TYPE'] =~ /^multipart\/related/ni
        puts env['rack.input'] # contain empty string "", but contain data after env['rack.input'].rewind
      end

      @app.call(env)
    end
  end
end
```

Middleware was included to rails app as usually:

```ruby
Rails.application.config.middleware.use(BlockPackage::Middleware)
```

Ruby version: 3.1.2
Rails version: 7.0.4.3
Rack version: 2.2.7
Puma version: >= 6.1.0

**Comment by willkoehler** [comment] 2023-05-10 12:43
Hi @sanzstez I can help look into this. The first step for me will be to reproduce locally. Is this something you can help with? Maybe we can setup a simple test app based on https://github.com/puma/puma/tree/master/benchmarks/local/sinatra

Any help you can provide helping me reproduce locally would be appreciated. Once I can do that, I should be able to take it from there.

**Comment by willkoehler** [comment] 2023-05-10 12:56
@sanzstez agreed, the Sinatra app might not work because of the Middleware. We could use a simple Rails app perhaps?

**Comment by MSP-Greg** [comment] 2023-05-10 13:04
@sanzstez

PR #3137 added some tests that would seem to cover this issue, but it's only in the master branch.  The issue fixed by the PR involved some encoding issues with uploads.  They used curl as a client, similar to the below:
```
"curl -H 'transfer-encoding: chunked' --form data=@#{temp_file_path} http://127.0.0.1:#{@port}/"
```

Might this be related?  If so, can you check this against Puma master?

**Comment by willkoehler** [comment] 2023-05-10 13:16
Thanks @MSP-Greg that certainly looks promising!

BTW I originally had `@read_buffer = String.new` in my PR but felt obligated to convert to `@read_buffer = +""` because of the Rubocop warning. It's interesting the unintended side-effects of optimizations like `Performance/UnfreezeString` I went along with it because it seemed harmless. I would have never guessed that `+""` would introduce a 'character/line-ending' sensitive side effect like that. Nice detective work 🙌

**Comment by sanzstez** [comment] 2023-05-10 13:26
@MSP-Greg @willkoehler I don't know why ... but it works from master! Checked few minutes ago. Can you please explain? (for understand)

**Comment by dentarg** [comment] 2023-05-11 19:42
Great, https://github.com/puma/puma/pull/3137 should be part of the next release. I'll close this.

**Closed by dentarg** 2023-05-11 19:42 UTC
Labels: duplicate
