### ISSUE TITLE
3.8.0: rails s -b 0.0.0.0 will set port to default puma port

### ISSUE THREAD

**Issue by noelblaschke** [puma/puma#1255] opened 2017-03-27 10:53 UTC
### Steps to reproduce

1) install rails with puma version 3.8.0/1/2
2) run `rails s -b 0.0.0.0`

### Expected behavior

Listening on tcp://0.0.0.0:3000

### Actual behavior

Listening on tcp://0.0.0.0:9292

### System configuration

In docker env:
**Ruby version**: 2.4.1
**Rails version**: 5.1.0rc1, not tested with 4.x

### Quick solution

Run `rails s -b 0.0.0.0 -p 3000`

**Comment by toshimaru** [comment] 2017-04-03 09:42
Same here. 

This was introduced by #1234 which adds 3 different sources of configuration. 

I tried to fix this, but I'm not sure my code is correct:

```rb
host = options[:Host] || default_options[:Host] || ::Puma::Configuration::DefaultTCPHost
port = options[:Port] || default_options[:Port] || ::Puma::Configuration::DefaultTCPPort
self.set_host_port_to_config(host, port, user_config)
```

(This code doesn't care default_config, so I'm not sure my code is correct)

**Comment by nateberkopec** [comment] 2017-04-07 16:28
Paging @schneems

**Comment by schneems** [comment] 2017-04-07 18:20
Well 💩. Thanks for the issue. I'll be able to take a look but it probably won't be for a few days I'm currently a bit sick.

**Comment by schneems** [comment] 2017-04-14 20:06
So. I'm seeing a different behavior:

```
$ rails s -b 0.0.0.0
/Users/schneems/.gem/ruby/2.4.1/gems/activesupport-5.0.1.rc2/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/Users/schneems/.gem/ruby/2.4.1/gems/activesupport-5.0.1.rc2/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
[tunemygc] not enabled
=> Booting Puma
=> Rails 5.0.1.rc2 application starting in development on http://0.0.0.0:3000
```

Can you give me an example app that reproduces the problem?

**Comment by tricknotes** [comment] 2017-04-16 16:13
@schneems 

You can see the full logs.

> Can you give me an example app that reproduces the problem?

here.

```
$ rails s -b 0.0.0.0
=> Booting Puma
=> Rails 5.1.0.rc1 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.3.3-p222), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop
```

I think this puma server listens `tcp://0.0.0.0:9292`, not `http://0.0.0.0:3000`.

This is the just generated rails application by the following command:
```
$ rails -v
Rails 5.1.0.rc1
$ rails new demo
```

**Comment by toshimaru** [comment] 2017-04-21 02:32
Seems this has been fixed in rails-side at Rails 5.1.0.rc1. 

see, https://github.com/rails/rails/pull/28513

```
$ rails s -b 0.0.0.0
=> Booting Puma
=> Rails 5.1.0.rc2 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.3.3-p222), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

**Comment by matiaskorhonen** [comment] 2017-04-24 11:24
This still seems to happen with Rails 5.1.0.rc2 (not sure who's fault it is, Rails or Puma…):

    » ./bin/rails s -b 0.0.0.0
    => Booting Puma
    => Rails 5.1.0.rc2 application starting in development on http://0.0.0.0:3000
    => Run `rails server -h` for more startup options
    Puma starting in single mode...
    * Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
    * Min threads: 5, max threads: 5
    * Environment: development
    * Listening on tcp://0.0.0.0:9292
    Use Ctrl-C to stop

**Comment by toshimaru** [comment] 2017-04-24 13:08
oh, sorry, I might be using my forked puma gem... It seems not fixed, I guess?

**Comment by matiaskorhonen** [comment] 2017-04-25 07:29
Just to confirm, I just tested this on a brand new Rails app generated with Rails 5.1.0.rc2 on Ruby 2.4.1 (on macOS Sierra). The same issue persists.

**Comment by schneems** [comment] 2017-04-25 22:48
Able to repro with rails master

```
$ rails s -b 0.0.0.0
=> Booting Puma
=> Rails 5.2.0.alpha application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:9292
```

**Comment by schneems** [comment] 2017-04-25 23:04
The issue is how we're doing defaults

```
          self.set_host_port_to_config(options[:Host], options[:Port], config: user_config)
          self.set_host_port_to_config(default_options[:Host], default_options[:Port], config: default_config)
```

What is happening is `options[:Host]` is `0.0.0.0`. However `options[:Port]` is blank, this is because 3000 is a default option and not supplied explicitly. It is passed along via `default_options[:Port]` which is `3000`.

Here's that method

```
      def self.set_host_port_to_config(host, port, config:, defaults:)
        if host && (host[0,1] == '.' || host[0,1] == '/')
          config.bind "unix://#{host}"
        elsif host && host =~ /^ssl:\/\//
          uri = URI.parse(host)
          uri.port ||= port || ::Puma::Configuration::DefaultTCPPort
          config.bind uri.to_s
        else

          if host
            port ||= ::Puma::Configuration::DefaultTCPPort
          end

          if port
            host ||= ::Puma::Configuration::DefaultTCPHost
            config.port port, host
          end
        end
      end
```

**Comment by asadakbar** [comment] 2017-04-27 23:06
We are hitting the same issue. Any thoughts as to a fix? For now we are explicitly setting the port in our docker spin up script.

**Comment by schneems** [comment] 2017-04-28 17:00
I attached a patch that will fix the issue, about 4 hours before you posted.

**Closed** 2017-05-01 16:54 UTC
