### ISSUE TITLE
Thread.abort_on_exception causes IOError

### ISSUE THREAD

**Issue by neilmiddleton** [puma/puma#558] opened 2014-07-22 13:10 UTC
See https://github.com/interagent/pliny/issues/52 for backstory.

Using a config that defines workers and threads, plus `Thread.abort_on_exception = true` often (but not always) causes this error.

```
[38952] - Worker 0 (pid: 38987) booted, phase: 0
[38952] - Worker 1 (pid: 38988) booted, phase: 0
[38952] - Worker 2 (pid: 38989) booted, phase: 0
^C[38952] - Gracefully shutting down workers...
D, [2014-07-22T13:58:01.971378 #38988] DEBUG -- : Terminating 3 actors...
D, [2014-07-22T13:58:01.971491 #38989] DEBUG -- : Terminating 3 actors...
D, [2014-07-22T13:58:01.971309 #38987] DEBUG -- : Terminating 3 actors...
/Users/neil/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.9.0/lib/puma/cluster.rb:213:in `write'/Users/neil/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.9.0/lib/puma/cluster.rb:213:in `write'/Users/neil/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.9.0/lib/puma/cluster.rb:213:in `write': closed stream (IOError)
	from /Users/neil/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.9.0/lib/puma/cluster.rb:213:in `<<'
: closed stream (: 	from /Users/neil/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.9.0/lib/puma/cluster.rb:213:in `block in worker'
IOErrorclosed stream)
 (IOError)
	from /Users/neil/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.9.0/lib/puma/cluster.rb:213:in `<<'
	from /Users/neil/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.9.0/lib/puma/cluster.rb:213:in `<<'
	from /Users/neil/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.9.0/lib/puma/cluster.rb:213:in `block in worker'
	from /Users/neil/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.9.0/lib/puma/cluster.rb:213:in `block in worker'
[38952] - Goodbye!
D, [2014-07-22T13:58:04.665570 #38952] DEBUG -- : Terminating 3 actors...
W, [2014-07-22T13:58:04.666560 #38952]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:callwait
```

**Comment by evanphx** [comment] 2015-08-15 01:08
This is most likely caused by the the primary thread closing and the worker threads finish up and seeing closed resources. `Thread.abort_on_exception` isn't really something people should be using with puma.

**Closed by evanphx** 2015-08-15 01:08 UTC
