### ISSUE TITLE
Tests stall quite often

### ISSUE THREAD

**Issue by dleidert** [puma/puma#2148] opened 2020-03-05 01:35 UTC
**Describe the bug**
I'm one of the Debian maintainers of puma. The 4.3 series has been uploaded to experimental. But often the build gets stuck when running the tests and must be terminated after 1,5 hours. `ps` for example shows this:

```
root       28222  0.0  0.0   2388   784 pts/1    S+   02:18   0:00 sh -c /usr/bin/ruby2.5 -w -I"test"  "/usr/lib/ruby/vendor_ruby/rake/rake_test_loader.rb" "test/test_app_status.rb" "test/test_binder.rb" "test/test_cli.rb" "test/test_config.rb" "test/test_events.rb" "test/test_http10.rb" "test/test_http11.rb" "test/test_integration_cluster.rb" "test/test_integration_pumactl.rb" "test/test_integration_single.rb" "test/test_iobuffer.rb" "test/test_launcher.rb" "test/test_minissl.rb" "test/test_null_io.rb" "test/test_persistent.rb" "test/test_plugin.rb" "test/test_puma_server.rb" "test/test_pumactl.rb" "test/test_rack_handler.rb" "test/test_rack_server.rb" "test/test_tcp_logger.rb" "test/test_tcp_rack.rb" "test/test_thread_pool.rb" "test/test_unix_socket.rb" "test/test_web_server.rb" -v
root       28223  9.6  0.2 3615992 47240 pts/1   Sl+  02:18   0:32 puma 4.3.3 (unix:///tmp/puma-test20200305-251-8k6mxn2) [tree]
```

It is not always the same test. Here are a few logs:

<https://salsa.debian.org/ruby-team/puma/-/jobs/594219>
<https://buildd.debian.org/status/package.php?p=puma&suite=experimental>
<https://buildd.debian.org/status/fetch.php?pkg=puma&arch=amd64&ver=4.3.1-1&stamp=1580998562&raw=0>
<https://buildd.debian.org/status/fetch.php?pkg=puma&arch=arm64&ver=4.3.1-1&stamp=1580998668&raw=0>

Any idea how to further track down the cause?

**To Reproduce**
I have no idea.

**Expected behavior**
Tests should run through without getting stuck.

**Desktop (please complete the following information):**
Debian Linux Sid (unstable)
puma 4.3.3

**Comment by nateberkopec** [comment] 2020-03-05 17:19
Thanks for your work and for all of your reports 👍

**Comment by nateberkopec** [comment] 2020-03-08 17:25
Your logs are weird. It almost looks like the suite is stalling _between_ tests. If it was stalling during a test, I would expect to see output like `TestPumaServer#test_http_11_close_without_body = 0.01 s =` (no dot at the end of the line).

**Comment by nateberkopec** [comment] 2020-03-08 20:03
Also, are you running with the CI env variable set? If you set CI to anything, we trigger test timeouts so tests get killed if they take longer than 30 seconds.

**Comment by dleidert** [comment] 2020-03-08 23:43
> Your logs are weird. It almost looks like the suite is stalling _between_ tests. If it was stalling during a test, I would expect to see output like `TestPumaServer#test_http_11_close_without_body = ` (no dot at the end of the line).

I can debug this a bit more. But I quoted such a case right at the top. The tests were stalled and `ps` showed a running `puma` server. When I killed it the tests continued. Is it possible, that tearing down the server stalls?

> Also, are you running with the CI env variable set? If you set CI to anything, we trigger test timeouts so tests get killed if they take longer than 30 seconds.

The build-daemons don't have the CI environment variable set. But I will enable it for testing. Maybe this gives us more information. Here is already one example:

<https://salsa.debian.org/ruby-team/puma/-/jobs/600810>
```
[..]
 TestPumaServer#test_timeout_in_data_phase = 2.00 s = .
[..]
 TestPumaServer#test_timeout_in_data_phase = 1.00 s = .
[..]
 TestPumaServer#test_timeout_in_data_phase:
 TimeoutEveryTestCase::TestTookTooLong: execution expired
     /builds/ruby-team/puma/debian/output/puma-4.3.3/test/test_puma_server.rb:334:in `gets'
     /builds/ruby-team/puma/debian/output/puma-4.3.3/test/test_puma_server.rb:334:in `test_timeout_in_data_phase'
```

I'll restart the tests for several times. Let's see, what happens.

**Comment by nateberkopec** [comment] 2020-03-08 23:52
> Is it possible, that tearing down the server stalls?

Certainly!

**Comment by dleidert** [comment] 2020-03-10 21:43
It is always TestPumaServer#test_timeout_in_data_phase() which triggers TimeoutEveryTestCase::TestTookTooLong.

**Comment by dleidert** [comment] 2020-10-16 00:48
puma now builds and tests without stalling reliably. I think this report can be closed.

**Comment by nateberkopec** [comment] 2020-10-16 13:29
That's great!!! All credit to @MSP-Greg for that + probably @wjordan's magical reactor refactor

**Comment by MSP-Greg** [comment] 2020-10-16 13:59
@dleidert

Sorry, I was going to ask last night, but it was an 'interesting' night in the US.

> puma now builds and tests without stalling reliably

You mentioned the 4.3.x series in the first post.  What version does your above comment refer to?

**Comment by dleidert** [comment] 2020-10-16 14:34
I packaged 4.6 recently.

**Comment by dleidert** [comment] 2020-10-16 23:49
Hm. It seems there is still a problem but not on the main architectures:

<https://buildd.debian.org/status/fetch.php?pkg=puma&arch=ppc64el&ver=4.3.6-1&stamp=1602819887&raw=0>
<https://buildd.debian.org/status/fetch.php?pkg=puma&arch=hurd-i386&ver=4.3.6-1&stamp=1602864791&raw=0>

At least on the hurd-i386 architecture the issue is persistent.

**Comment by LocutusOfBorg** [comment] 2020-12-03 17:53
Looks like also Ubuntu on s390x is having the very same issue.
https://launchpad.net/ubuntu/+source/puma/4.3.6-1ubuntu1/+build/20360561

This morning I found that on amd64 arm64 and ppc64el IIRC. Retrying builds helped everywhere except for s390x, where the issue is persistent.

**Comment by lucaskanashiro** [comment] 2021-03-01 15:09
In Ubuntu I've seen this test timing out multiple times at least on s390x, arm64, and ppc64el architectures (this after setting the `CI` environment variable as explained above):

```
TestPumaServer#test_timeout_in_data_phase:
TimeoutEveryTestCase::TestTookTooLong: execution expired
    /tmp/autopkgtest.ykFkDS/build.VMv/real-tree/test/test_puma_server.rb:334:in `gets'
    /tmp/autopkgtest.ykFkDS/build.VMv/real-tree/test/test_puma_server.rb:334:in `test_timeout_in_data_phase'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:98:in `block (3 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:195:in `capture_exceptions'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:95:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:270:in `time_it'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:94:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:365:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:211:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:93:in `run'
    /tmp/autopkgtest.ykFkDS/build.VMv/real-tree/test/helper.rb:67:in `block in run'
```

**Comment by dentarg** [comment] 2021-03-01 16:29
@lucaskanashiro are your CI logs public? Have you tried running the tests not in parallel? (it’s default IIRC, not sure how to change it, but shouldn’t be that tricky)

**Comment by MSP-Greg** [comment] 2021-03-01 16:44
@lucaskanashiro

Thanks for info.  We've also had intermittent failures running in GitHub Actions.

Can you test Puma from a git repo?

I've been working on an update to the test suite, and it still has intermittent failures, but they seem to be with older Ruby versions (2.4 and earlier)...

The branch is https://github.com/MSP-Greg/puma/tree/test-update

**Comment by lucaskanashiro** [comment] 2021-03-01 18:48
> @lucaskanashiro are your CI logs public?

Unfortunately not, I was running the tests in a VM locally (setting the `CI` environment variable). If you want the full log I can re-ran and copy&paste it.

In the public logs we have the tests are hanging forever, and then our CI system timed out after almost 3h running:

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-hirsute/hirsute/s390x/p/puma/20210226_214456_196ae@/log.gz

> Have you tried running the tests not in parallel? (it’s default IIRC, not sure how to change it, but shouldn’t be that tricky)

I do not know exactly how to do it. Any tips?

**Comment by lucaskanashiro** [comment] 2021-03-01 18:49
> @lucaskanashiro
> 
> Thanks for info. We've also had intermittent failures running in GitHub Actions.
> 
> Can you test Puma from a git repo?
> 
> I've been working on an update to the test suite, and it still has intermittent failures, but they seem to be with older Ruby versions (2.4 and earlier)...
> 
> The branch is https://github.com/MSP-Greg/puma/tree/test-update

Definitely. I'll give a shot and let you know the results.

**Comment by lucaskanashiro** [comment] 2021-03-01 19:06
@MSP-Greg the results of the tests using your `test-update` branch on s390x and arm64 VMs:

```
ubuntu@puma-s390x-debug:~/upstream/puma$ git branch
  master
* test-update
ubuntu@puma-s390x-debug:~/upstream/puma$ bundle exec rake test:all
install -c tmp/s390x-linux-gnu/puma_http11/2.7.2/puma_http11.so lib/puma/puma_http11.so
cp tmp/s390x-linux-gnu/puma_http11/2.7.2/puma_http11.so tmp/s390x-linux-gnu/stage/lib/puma/puma_http11.so

ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [s390x-linux-gnu]
RUBYOPT: -r/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/setup
                         Puma::MiniSSL                   OpenSSL
OPENSSL_LIBRARY_VERSION: OpenSSL 1.1.1f  31 Mar 2020     OpenSSL 1.1.1f  31 Mar 2020
        OPENSSL_VERSION: OpenSSL 1.1.1f  31 Mar 2020     OpenSSL 1.1.1f  31 Mar 2020

Run options: --seed 51076

# Running:

......................................................................EE..
Open IO issues
Bad Init  Open  Closed    Class
      0      3       8    IO
      0      1       0    TestPuma::SktTCP
      0      0       4    UNIXServer
rake aborted!
Command failed with status (1)
/home/ubuntu/upstream/puma/vendor/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => test:all => test
(See full trace by running task with --trace)
```

```
ubuntu@puma-arm64-debug:~/upstream/puma$ git branch
  master
* test-update
ubuntu@puma-arm64-debug:~/upstream/puma$ bundle exec rake test:all
install -c tmp/aarch64-linux-gnu/puma_http11/2.7.2/puma_http11.so lib/puma/puma_http11.so
cp tmp/aarch64-linux-gnu/puma_http11/2.7.2/puma_http11.so tmp/aarch64-linux-gnu/stage/lib/puma/puma_http11.so

ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [aarch64-linux-gnu]
RUBYOPT: -r/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/setup
                         Puma::MiniSSL                   OpenSSL
OPENSSL_LIBRARY_VERSION: OpenSSL 1.1.1f  31 Mar 2020     OpenSSL 1.1.1f  31 Mar 2020
        OPENSSL_VERSION: OpenSSL 1.1.1f  31 Mar 2020     OpenSSL 1.1.1f  31 Mar 2020

Run options: --seed 49368

# Running:

.................................................................................................................................EE...................
Open IO issues
Bad Init  Open  Closed    Class
      0      3       7    IO
      0      0       2    TCPServer
      0      1       0    TestPuma::SktTCP
      0      0       2    UNIXServer
rake aborted!
Command failed with status (1)
/home/ubuntu/upstream/puma/vendor/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => test:all => test
(See full trace by running task with --trace)
```

If you need any extra info just let me know and I can get it for you.

**Comment by MSP-Greg** [comment] 2021-03-01 19:14
@lucaskanashiro 

It looks like the two errors aren't intermittent?

Can you run the tests with `-v` or `--verbose`?  Setting  `TESTOPTS=-v` should change that.  

An uncaught error seems to be crashing the reporting, the full log may give some clues to what's causing it.

Thanks again, very helpful...

**Comment by lucaskanashiro** [comment] 2021-03-01 19:31
Here is the output using the verbose mode:

https://paste.ubuntu.com/p/KHwWxD6ksw/

It seems that `TestWorkerGemIndependence#test_changing_json_version_during_phased_restart_after_querying_thread_backtraces_from_status_server` is the problematic test.

**Comment by MSP-Greg** [comment] 2021-03-01 20:02
@lucaskanashiro

Thanks.  Almost all the CI we run updates bundler.  Not sure about whether that could be the cause or not.

Part of what `TestWorkerGemIndependence` tests is changing versions of Puma dependencies during restarts, so it creates folders, symlinks, runs `bundle install` in those folders, etc.  Of course, haven't had an issue running it locally or on Actions CI.

I'll look at it more later.  Are you running with a local copy or pulling from GitHub with each run?  Wondering about bypassing that test file and seeing if the other tests are stable...

Not sure how much you can help, but I can rename it in my fork.

Thanks again.

@cjlarose - if you have a minute...

**Comment by lucaskanashiro** [comment] 2021-03-01 20:54
@MSP-Greg

I applied a patch skipping the failing test:

```
diff --git a/test/test_worker_gem_independence.rb b/test/test_worker_gem_independence.rb
index b12a5373..b6adf643 100644
--- a/test/test_worker_gem_independence.rb
+++ b/test/test_worker_gem_independence.rb
@@ -50,6 +50,7 @@ class TestWorkerGemIndependence < ::TestPuma::SvrPOpen
   end
 
   def test_changing_json_version_during_phased_restart_after_querying_thread_backtraces_from_status_server
+    skip "Ignore this test for now"
     ctrl_type :tcp
     before_restart = ->() do
       cli_pumactl "thread-backtraces"
```

And the re-ran the tests in verbose mode. Here is the output:

https://paste.ubuntu.com/p/RJHssxMXBX/

**Comment by MSP-Greg** [comment] 2021-03-01 21:29
Thanks.

Interesting that the tests are aborting and the summary isn't shown.  I've ran them a lot locally (Windows WSL2/20.04) and also in GitHub Actions, and that doesn't happen often.  So, I need to figure out why that's happening...

Re Ubuntu test systems, the GitHub machines have `ulimit -n` of 64k.  Is that typical?

**Comment by lucaskanashiro** [comment] 2021-03-01 21:46
@MSP-Greg

Did you test it on non-amd64 architectures via WSL2?

I do not have the answer right now for the Ubuntu test infrastructure, but at least in my testing VMs I get this:

```
ubuntu@puma-s390x-debug:~/upstream/puma$ ulimit -n
1024
```

**Comment by MSP-Greg** [comment] 2021-03-01 22:05
@lucaskanashiro

Sorry, I'm using a Windows system, so I'm on an Intel i9.  That's all I can test on locally, and we're using GitHub Actions, which, at present, is only amd64.

One thing I wanted to change in the updated tests was having some tests that open a lot of clients, as this wasn't done previously.  Web/app servers often won't have issues with a handful of clients, but they may have issues when there are hundreds or thousands of clients.

```
ubuntu@puma-s390x-debug:~/upstream/puma$ ulimit -n
1024
```

I may need to reconsider it, but I don't think the tests will run with a setting that low.  Probably needs to be at least 4k, I run them with 32k.  That may be the reason the tests are aborting...

**Comment by lucaskanashiro** [comment] 2021-03-02 00:33
I got an answer about the `ulimit -n` in our testbed: `should be the default for Ubuntu, which is 1024 soft limit and 1048576 hard limit AFAIR`

**Comment by MSP-Greg** [comment] 2021-03-02 00:52
Just to be clear (and you probably know this), the limit only affects how many active client/connections Puma can have, but, since Puma is really 'server' software, we'd like to test it as such.  IOW, Puma doesn't require the higher limits, but the tests do.

We'd certainly like Puma to run on any platform that Ruby runs on, so I'd like to help work through this.  I can add some ENV setting to lower the connection/client count, but that's kind of a PITA.  Maybe a multiplier could be added, so you could figure out a setting that works on your testbed?

Lastly, the fork is based on Puma master.  What affects the decision as to which Puma version is used?  Or, how can we help with moving to Puma 5.x instead of 4.3.6?

Lastly, below is a link to the most recent Actions job on Ubuntu 20.04 & Ruby 2.7:
https://github.com/MSP-Greg/puma/runs/2005586662?check_suite_focus=true#step:9:20

All the data for the client tests is normally hidden, you need to click open line 547 'Debugging Info'.  Notice the times for clients, I think the low limit is what may be slowing your testbed down, and it finally chokes?

**Comment by lucaskanashiro** [comment] 2021-03-02 18:24
> Just to be clear (and you probably know this), the limit only affects how many active client/connections Puma can have, but, since Puma is really 'server' software, we'd like to test it as such. IOW, Puma doesn't require the higher limits, but the tests do.

Maybe you could have a new rake task to run only high intensive tests to stress the server?

> We'd certainly like Puma to run on any platform that Ruby runs on, so I'd like to help work through this. I can add some ENV setting to lower the connection/client count, but that's kind of a PITA. Maybe a multiplier could be added, so you could figure out a setting that works on your testbed?

That'd be a solution as well.

> Lastly, the fork is based on Puma master. What affects the decision as to which Puma version is used? Or, how can we help with moving to Puma 5.x instead of 4.3.6?

In Ubuntu, we in general follow Debian's decision, which seems to be 4.3.6 for the next Debian release. Both, Ubuntu and Debian, are in a feature freeze process at the moment to stabilize everything before releasing, therefore, I believe Puma 5.x will need to wait for the next cycle.

> Lastly, below is a link to the most recent Actions job on Ubuntu 20.04 & Ruby 2.7:
> https://github.com/MSP-Greg/puma/runs/2005586662?check_suite_focus=true#step:9:20

Thanks for the link.

> All the data for the client tests is normally hidden, you need to click open line 547 'Debugging Info'. Notice the times for clients, I think the low limit is what may be slowing your testbed down, and it finally chokes?

Yes, that might be the an issue in this case.

**Comment by MSP-Greg** [comment] 2021-03-02 19:21
1. I think the tests might run if `ulimit -Sn 4096` is successful.  They did so locally.  Not sure if the testbed systems will allow that.  I set my system to a higher limit as I'm often testing with a lot of clients.

2. I made a couple of small changes to the `TestWorkerGemIndependence` file, they may help.  There could have been a race condition, not sure (can't get it to fail).  You can run individual tests with:
```
bundle exec rake test TESTOPTS=--verbose TEST=test/test_worker_gem_independence.rb
```
Also, I added some debugging to those tests, setting `PUMA_CI_WORKER_GEM_INDEPENDENCE` will dump all output from the server and the STDOUT & STDERR from the bundle commands used in the tests.

Re the Puma version, I suspect most people wanting to use Puma will install a current gem.  But, it would be helpful to know that master passes.

Do you know of any publicly facing s390x, arm64, and ppc64el servers that can be used for CI?  Not for every commit, but maybe once a week test against master...

Thanks, Greg

**Comment by lucaskanashiro** [comment] 2021-03-05 12:50
Unfortunately, I can't change the default testbed settings.

I ran the test you mentioned in my s390x VM and it failed, here is the output:

https://paste.ubuntu.com/p/KYCGZ6ZB4R/

After a quick look, I learned that travis CI can run tests on multiple architectures. Take a look at this doc:

https://docs.travis-ci.com/user/multi-cpu-architectures/

**Comment by dentarg** [comment] 2021-12-13 19:17
Going to close this one, but feel free to open new issues @lucaskanashiro @dleidert if you have any recent problems with the tests.

Re: different architectures, I don't think we're going back to Travis CI, but maybe we can use Docker+QEMU (e.g. https://github.com/uraimo/run-on-arch-action) on GitHub Actions.

**Closed by dentarg** 2021-12-13 19:17 UTC
Labels: bug, maintenance
