### ISSUE TITLE
Puma concurrency issue

### ISSUE THREAD

**Issue by BenJaziaSadok** [puma/puma#1245] opened 2017-03-16 12:22 UTC
Hello, 
I have a puma server running 4 workers and default thread number.
Then in my rails app, i have a method that creates an object depending of a database value.
This works fine in most cases.
But in some cases i have an unexpected behavior which is the object is created many time (3 or 4 time) and broke the app.
Do you think it's a concurrency issue, or multithreading issue, does implementing a Mutex is a good idea.
Can you suggest me some ideas ?

**Comment by nateberkopec** [comment] 2017-03-19 01:33
Yes - this is a multithreading issue. Since this is not a bug with Puma, I'm closing. There are many resource for multithreaded programming in Ruby and Rails online.

**Closed by nateberkopec** 2017-03-19 01:33 UTC
