### ISSUE TITLE
4.3.2 update broke devise authenticated root route

### ISSUE THREAD

**Issue by CrazybutSolid** [puma/puma#2138] opened 2020-02-28 20:31 UTC
Apologies for the lack of details, not an advanced programmer.

**Describe the bug**
Updated from Puma 4.3.1 to 4.3.2

After the update, when signing up or signing into my website, puma would always take me to the unauthenticated root.

Downgraded to 4.3.1 and everything is fine again.

**Puma config:**

Puma 4.3.2

```
run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }
```

Run it with:

```
bundle exec puma -C <where_your_config_is> hello.ru
```

If you cannot reproduce with a hello world application or other simple application, we will have a lot more difficulty helping you fix your issue, because it may be application-specific and not a bug in Puma at all.  

There is also a Dockerfile available for reproducing Linux-specific issues. To use:

```
$ docker build -f tools/docker/Dockerfile -t puma .
$ docker run -p 9292:9292 -it puma
```

This will help you to create a container that reproduces your issue.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux]
 - Puma Version [e.g. 4.1.1]

**Comment by nateberkopec** [comment] 2020-02-28 20:41
Duplicate of #2132, please upgrade to 4.3.3.

**Closed by nateberkopec** 2020-02-28 20:41 UTC

**Comment by ccasabona** [comment] 2020-02-28 20:43
Puma 4.3.2 also broke our login redirect (not using devise).  Puma 4.3.3 came through while writing this post.  This version is working correctly.
