### ISSUE TITLE
Puma does not load a CA when verification mode is set to :peer

### ISSUE THREAD

**Issue by seanmckinley** [puma/puma#1222] opened 2017-02-20 17:31 UTC
### Steps to reproduce

1) Configure Puma to accept SSL connections:
```
key =  File.expand_path "./certs/my_key.key"
cert = File.expand_path "./certs/my_cert.crt"
ca = File.expand_path "./certs/my_ca.crt"

ssl_bind "0.0.0.0", 9292, :ca => ca, :cert => cert, :key => key, :verify_mode => :peer
```

2) Start Puma, and get the following:
```
 starting in single mode...
* Version 3.6.2 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: production
ERROR: Please specify the SSL ca via 'ca='
```

### Expected behavior

Puma should just start and accept TLS connections.

### Actual behavior

Puma exits 1, requesting a CA be specified.

### Why it's happening

If mode is set to verify a peer, it requests a CA:
https://github.com/puma/puma/blob/0912b0cea1576e96ee4e84a84cfff2a80750ecf6/lib/puma/binder.rb#L178

However, the ssl bind method will not attach a CA param to the URL it generates:
https://github.com/puma/puma/blob/master/lib/puma/dsl.rb#L273

If this is a bug and not just me being dumb/wrong, I have no problem submitting a PR to fix it. 

### System configuration

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768)
**Rails version**: rails (5.0.1)

**Comment by nateberkopec** [comment] 2017-03-03 16:51
Looks like a bug.

**Comment by fruwe** [comment] 2017-05-27 15:05
👍

**Comment by fruwe** [comment] 2017-05-27 15:18
temporarily can be fixed by using bind instead of ssl_bind like this:

```
ssl_options = {
  ca: "xxx/yyy.cer",
  cert: "xxx/yyy.crt",
  key: "xxx/yyy.key",
  verify_mode: 'peer',
}

# ssl_bind '0.0.0.0', '443', ssl_options
bind "ssl://0.0.0.0:443?cert=#{ssl_options[:cert]}&key=#{ssl_options[:key]}&verify_mode=#{ssl_options[:verify_mode]}&ca=#{ssl_options[:ca]}"
```

**Comment by MikaelSmith** [comment] 2018-08-22 20:47
I'd also like to be able to set both ca and verify_mode (when not using Java as well).

**Comment by karlwilbur** [comment] 2019-03-17 06:57
Still not working with `ssl_bind` as of latest Puma 3.12.0 (I mention is because the title explicitly states 3.6.2):

https://github.com/puma/puma/blob/v3.12.0/lib/puma/dsl.rb#L286-L295

**Comment by iovis** [comment] 2019-10-04 15:05
Can reproduce:
Puma 4.2.0
Ruby 2.6.3

```rb
# config.rb
key =  File.expand_path "./certs/my_key.key"
cert = File.expand_path "./certs/my_cert.crt"
ca = File.expand_path "./certs/my_ca.crt"

ssl_bind "0.0.0.0", 9292, :ca => ca, :cert => cert, :key => key, :verify_mode => :peer
```

I created three empty files for the certs and then run:

```sh
bundle exec bin/puma -C config.rb test/rackup/hello.ru
```

**Closed** 2019-10-04 17:30 UTC
Labels: bug, contrib-wanted, ssl
