### ISSUE TITLE
Puma fails to restart when starting with rails s - rails usage shown instead

### ISSUE THREAD

**Issue by obfuscoder** [puma/puma#1298] opened 2017-05-22 08:57 UTC
### Steps to reproduce

1) Add puma to Gemfile, add config/puma.rb with activated tmp_restart plugin. Example project at https://github.com/obfuscoder/flee_rails

2) Start server with rails s. Puma starts:

```
=> Booting Puma
=> Rails 4.2.8 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[16644] Puma starting in cluster mode...
[16644] * Version 3.8.2 (ruby 2.2.5-p319), codename: Sassy Salamander
...
```

3) Restart with touching tmp/restart.txt or kill -USR2 <pid>

### Expected behavior

Puma should detect restart.txt and restart.

### Actual behavior

Puma detects restart.txt and tries to restart, but fails. The standard rails howto is printed on console instead which is shown when starting rails without argument:

```
[16263] - Gracefully shutting down workers...
[16263] * Restarting...
Usage: rails COMMAND [ARGS]

The most common rails commands are:
...
```

It does not matter whether I try to restart with restart.txt or SIGUSR2.

### System configuration

**Ruby version**: ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin14]
**Rails version**: Rails 4.2.8

**Comment by steakknife** [comment] 2017-05-28 21:24
This is a duplicate of #1060

**Comment by steakknife** [comment] 2017-05-28 21:29
Restarting by restart.txt when using rails s is broken. Don't use it, use pumactl

There are rack and puma PRs that have been open over a year, but it still isnt fixed in any PR because there are more bugs.

**Comment by prathamesh-sonpatki** [comment] 2017-06-02 05:33
The restart support was added in Rails 5, so it won't work with Rails 4.2.8.

**Comment by nateberkopec** [comment] 2017-06-02 12:50
I'm closing this because Rails 4.2 is now on "severe security updates only", so I don't see a point in taking maintainer time for trying to patch this for Rails 4.2.

**Closed by nateberkopec** 2017-06-02 12:50 UTC
