### ISSUE TITLE
not cleanly closing ssl sockets on phased_restart?

### ISSUE THREAD

**Issue by mattyb** [puma/puma#1002] opened 2016-06-16 20:00 UTC
We're running apache bench against a running puma server bound to ssl sockets. When we perform a puma phased restart, we get a batch of SSL errors in apache bench each time a worker goes down. With verbose ab flags, a healthy connection includes messages like

```
SSL/TLS State [connect] SSLv3 flush data
read from 0x7f1e770b74e0 [0x7f1e770aab33] (5 bytes => -1 (0xFFFFFFFFFFFFFFFF))
read from 0x7f1e770b74e0 [0x7f1e770aab33] (5 bytes => 5 (0x5))
0000 - 16 03 03 00 aa                                    .....
```

Where a failed connection looks like
```
SSL/TLS State [connect] SSLv3 flush data
read from 0x7f1e770b77a0 [0x7f1e770aab33] (5 bytes => -1 (0xFFFFFFFFFFFFFFFF))
read from 0x7f1e770b77a0 [0x7f1e770aab33] (5 bytes => 0 (0x0))
SSL handshake failed (5).
```

I believe that this is the reason that our AWS ELB returns 504 errors each time we perform a phased restart. cc @timabdulla, who reported similar symptoms in #957

**Comment by evanphx** [comment] 2016-07-24 04:42
If it's the same issue as #957, you can configured the persistent_timeout now. Please try that and if it doesn't work, reopen this issue.

**Comment by mattyb** [comment] 2016-07-24 13:38
Thanks @evanphx, but adjusting timeouts doesn't affect this. This error occurs without going through the ELB.

**Comment by evanphx** [comment] 2016-07-24 20:11
Hm, ok. I wonder if perhaps on a worker exit persistent sockets aren't being closed. That's not an issue for normal HTTP sockets because the process exit will close the socket, but would be an issue for SSL sockets because the close actually sends data back across telling the other side that it's closed. I'll investigate.

**Comment by evanphx** [comment] 2016-07-25 03:43
Nope, `close` is called on all sockets. Oh, are you using actioncable or websockets or something else that perhaps uses hijack? If so, I'm betting they're not closing the sockets down on shutdown...

**Comment by mattyb** [comment] 2016-07-25 14:24
I've reproduced the error with just a puma config file (no rack app) here: https://github.com/mattyb/puma-socket-test

**Comment by evanphx** [comment] 2016-07-25 22:43
Thanks so much for the reproduction! I'm working on it now.

**Comment by evanphx** [comment] 2016-07-26 01:45
@mattyb That should fix your problem. Do you have a way to try it out easily before I release the fix?

**Closed** 2016-07-26 01:45 UTC
Labels: Needs Feedback

**Comment by mattyb** [comment] 2016-07-26 05:29
Thanks for working on this! I no longer see the SSL errors popping up in the console and there are new messages in the verbose logs about connections being closed. Unfortunately, even with the reproduction code updated to the 46416cb commit, I still see failed requests from `ab`.

```
Concurrency Level:      25
Time taken for tests:   21.217 seconds
Complete requests:      3000
Failed requests:        21
   (Connect: 0, Receive: 0, Length: 21, Exceptions: 0)
```

It's possible that this is a problem with `ab`'s implementation, though I believe I'm using the latest version. I confirmed that there are no errors if I bind tcp without ssl. I assume the fact that all the errors are failures in "Length" is relevant.

I could try the new commit on our real app in our staging environment and see if the ELB handles whatever error is happening more cleanly, but it seems like something may still be awry in puma.
