### ISSUE TITLE
Bind is ignored when starting Rails with foreman

### ISSUE THREAD

**Issue by celsodantas** [puma/puma#1771] opened 2019-04-11 20:35 UTC
### Steps to reproduce

1) rails new foremanapp

2) add `gem 'foreman'` to Gemfile

3) add file `Procfile` with `web: bin/rails server`

4) add `bind 'unix:///tmp/puma.sock'` to `puma.rb`

5) run `foreman start`

the output:

```
☺  foreman start
22:32:43 web.1  | started with pid 55143
22:32:44 web.1  | => Booting Puma
22:32:44 web.1  | => Rails 5.2.3 application starting in development
22:32:44 web.1  | => Run `rails server -h` for more startup options
22:32:45 web.1  | Puma starting in single mode...
22:32:45 web.1  | * Version 3.12.1 (ruby 2.5.1-p57), codename: Llamas in Pajamas
22:32:45 web.1  | * Min threads: 5, max threads: 5
22:32:45 web.1  | * Environment: development
22:32:45 web.1  | * Listening on tcp://localhost:5000
22:32:45 web.1  | Use Ctrl-C to stop
```

### Expected behavior

It should bind to `unix:///tmp/puma.sock` but it's being ignored.

### Actual behavior

In comparison:

```
rails s
=> Booting Puma
=> Rails 5.2.3 application starting in development
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.12.1 (ruby 2.5.1-p57), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
* Listening on unix:///tmp/puma.sock
```

By the way, if `bundle exec puma -C config/puma.rb` is used in the `Procfile` instead, the binding works fine.

### System configuration

**Ruby version**: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]`
**Rails version**: `Rails 5.2.3`
**Puma version**: `puma (3.12.1)`

---

I'm still investigating the issue but I'm not sure if this is Rails or Puma issue, and why foreman is changing the binding behaviour. Edit: I think this is an issue in Rails but I'll leave this here for other people to find as well.

**Comment by celsodantas** [comment] 2019-04-12 08:39
Extra information is that `foreman` by default passes an ENV var `PORT=5000`, it looks like that is causing the binding to be dropped, because if I do `PORT=5000 rails server` same issue happens.

**Comment by celsodantas** [comment] 2019-04-12 09:29
https://github.com/puma/puma/blob/6e7d38540ffada91355498c9abe0c98f1d22b9e1/lib/puma/configuration.rb#L57

This line is caused the `bind` to be ignored. From what I understand, the `PORT` param goes into the `user_options` and takes precedence. Don't know yet why running `bundle exec puma -C config/puma.rb` doesn't cause that, tho.

**Comment by dannyfallon** [comment] 2019-05-15 22:37
When using Puma directly via the CLI `user_options` is read from command line arguments passed in. So `puma -p 5000 -C config/puma.rb` produces the same outcome as you reported:

```
➜  foremanapp git:(master) ✗ bundle exec puma -C config/puma.rb -p 5000
Puma starting in single mode...
* Version 3.12.1 (ruby 2.5.5-p157), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:5000
Use Ctrl-C to stop
```


`Rack::Handler::Puma#run` is invoked by `Rails::Server` with `user_supplied_options = [:Port]` [due to ENV["PORT"] being set](https://github.com/rails/rails/blob/1cdc6c6576afe9a9fa67a6b313080a7dc62188d9/railties/lib/rails/commands/server/server_command.rb#L208-L210) by `foreman`.

All `user_supplied_options` eventually make their way into the `user_options` instance variable of [`Puma::UserFileDefaultOptions`](https://github.com/puma/puma/blob/6e7d38540ffada91355498c9abe0c98f1d22b9e1/lib/puma/configuration.rb#L134). Before it gets there though, they're run through the DSL...

[`Puma::Configuration::DSL#port`](https://github.com/puma/puma/blob/6e7d38540ffada91355498c9abe0c98f1d22b9e1/lib/puma/dsl.rb#L152-L155) calls [`Puma::DSL#bind`](https://github.com/puma/puma/blob/6e7d38540ffada91355498c9abe0c98f1d22b9e1/lib/puma/dsl.rb#L141-L144) which will set the `options[:binds]` of the DSL object to `["tcp://localhost:5000"]`.

As rightly pointed out, `Puma::UserFileDefaultOptions#[]` defines [an order of precedence](https://github.com/puma/puma/blob/6e7d38540ffada91355498c9abe0c98f1d22b9e1/lib/puma/configuration.rb#L56-L60):

```
def [](key)
      return user_options[key]    if user_options.key?(key)
      return file_options[key]    if file_options.key?(key)
      return default_options[key] if default_options.key?(key)
end
```

While `file_options[:binds]` is set successfully set to `["tcp://localhost:3000", "unix:///tmp/puma.sock"]` as per the `config/puma.rb` (which does get parsed and loaded!), Puma's going to use `user_options[:binds]` over it.

From what I can see Foreman does not give you a way to not set `ENV["PORT]` and `rails server` does not appear to give you a way to set the binding to a socket via a command line arg like you can with `Puma::CLI` so you're in a catch 22.

**Comment by ErvalhouS** [comment] 2019-05-24 14:30
Confirmed to existence of this bug with version `3.11.0` running with Rails `~>5.1`

**Comment by nateberkopec** [comment] 2019-05-24 23:38
Assigning to @schneems as config is kind of his wheelhouse

**Comment by schneems** [comment] 2019-06-05 19:29
Hello 👋 . I don't think we can "know" when the PORT env var is a default and versus when it's legit wanted behavior.

When you specify more than one bind in puma it connects to all of them instead of over-writing the prior, so in this case you're actually still binding to the correct port:

```
* Listening on tcp://localhost:3000
* Listening on unix:///tmp/puma.sock
```
> Notice that it's using the unix socket too

Now the downside is if you're trying to run multiple things on the same machine then having one port open on 5000 would stop others from being open.

You can work around this by using this in your procfile:

```
web: unset PORT && bin/puma -C config/puma.rb
```

Short of adding a feature to the DSL like:

```
force_bind "unix://whatever"
```

We can't really fix this "bug" for now. Even a DSL change would be tricky due to the way that puma loads its config.

I'm open to suggestions, but i'm going to close this for now, I know it's not ideal but at least a work around exists.

**Closed by schneems** 2019-06-05 19:29 UTC
Labels: bug

**Comment by PabloC** [comment] 2021-02-10 21:51
Thank you all, it was helpful to know that Foreman adds a PORT env. The unset workaround is great.

**Comment by dorianmariefr** [comment] 2021-12-10 22:55
I do in my `Procfile`s:

```
web: unset PORT && rails s
```

works really nice, thanks @schneems

**Comment by miguno** [comment] 2025-05-08 10:30
The workaround with `unset PORT` in https://github.com/puma/puma/issues/1771#issuecomment-991357734 worked for me in May 2025 with Rails 8.0.2. Thanks!
