### ISSUE TITLE
Infinite loop in Puma reactor IO.select 

### ISSUE THREAD

**Issue by asrivatsava** [puma/puma#1657] opened 2018-10-05 22:00 UTC
Found an issue in Puma reactor.rb. There is an infinite loop on IO.select reading from Socket buffer. This is happening because of a timeout of 0 is getting passed to IO.select. And its in a infinite loop of reactor’s method: ‘run_internal’.

We have a internal proxy service which runs in Puma. And every third day or so we see the CPU usage go to 100% and end up restarting the Server. The Puma proxy server is deployed in Kubernetes cluster and the service sits behind Nginx proxy exposed outside.

Every 2-3 days we see 2-3 pods get hung with 100% CPU and we end up restarting the cluster. Any help is appreciated or anyone experiencing the same?

ready = IO.select sockets, nil, nil, @sleep_for

```
def run_internal
      sockets = @sockets

      while true
        begin
          ready = IO.select sockets, nil, nil, @sleep_for
        rescue IOError => e
          Thread.current.purge_interrupt_queue if Thread.current.respond_to? :purge_interrupt_queue
          if sockets.any? { |socket| socket.closed? }
            STDERR.puts "Error in select: #{e.message} (#{e.class})"
            STDERR.puts e.backtrace
            sockets = sockets.reject { |socket| socket.closed? }
            retry
          else
            raise
          end
        end
```

And based on the threads captured during high loads using rbtrace, the following lines point to the infinite loop of IO.select

/home/jiff_user/.bundle_cache/gems/puma-3.11.4/lib/puma/reactor.rb:29:in `select'
/home/jiff_user/.bundle_cache/gems/puma-3.11.4/lib/puma/reactor.rb:29:in `run_internal'

The @sleep_for is calculated in

```
def calculate_sleep
     if @timeouts.empty?
        @sleep_for = DefaultSleepFor
      else
        diff = @timeouts.first.timeout_at.to_f - Time.now.to_f

        if diff < 0.0
          @sleep_for = 0
        else
          @sleep_for = diff
        end
      end
 end
```

And from Puma documentation
'Once all the timeouts have been processed, the next duration of the `IO.select` sleep
will be set to be equal to the amount of time it will take for the next timeout to occur.This calculation happens in `calculate_sleep`.’

“If that value is in the past, then a sleep value of zero is used.”

A sleep value of 0 would make the IO.select read on the socket buffer infinitely

When tried on my local, I could see the @sleep_for value go to zero:
```
Run INTERNAL>>>>>>>>>>>>>>i 0.230482816696167
$$$$$$$$$$$$$TIMEOUTS: 52$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
Run INTERNAL>>>>>>>>>>>>>>i 0.005938053131103516
$$$$$$$$$$$$$TIMEOUTS: 51$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
Run INTERNAL>>>>>>>>>>>>>>i 0.46006107330322266
$$$$$$$$$$$$$TIMEOUTS: 50$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$TIMEOUTS: 49$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
Run INTERNAL>>>>>>>>>>>>>>i 0.4800748825073242
$$$$$$$$$$$$$TIMEOUTS: 48$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
Run INTERNAL>>>>>>>>>>>>>>i 0.0007088184356689453
$$$$$$$$$$$$$TIMEOUTS: 47$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
Run INTERNAL>>>>>>>>>>>>>>i 0.5106768608093262
$$$$$$$$$$$$$TIMEOUTS: 46$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
Run INTERNAL>>>>>>>>>>>>>>I 0(ZERO SLEEP ON IO.select)
$$$$$$$$$$$$$TIMEOUTS: 45$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$TIMEOUTS: 44$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
Run INTERNAL>>>>>>>>>>>>>>i 0.0038771629333496094
$$$$$$$$$$$$$TIMEOUTS: 43$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
```

So if the client requests have timeout in the past the sleep is set to zero. And since this happens over a 3day period..I think the requests are queueing up in Proxy Puma server and getting timeout when downstream servers don’t respond in time. And overtime these timeouts make the reactor run IO.select infinitely with the sleep value of 0.

### System configuration

**Ruby version**:2.5.1
**Puma version**:3.11.4 or 3.12.0 with queue_request=true

**Comment by Jesus** [comment] 2019-05-27 17:43
Is there any way we can reproduce this?

Also, this may no longer be a problem since the [reactor changed recently](https://github.com/puma/puma/pull/1728). But still I'd like to understand what's going on.

I'm currently digging into the source code and wondering why would someone use a timeout of 0 intentionally (as there's a explicit statement for this). I'll update this when I have more answers...

**Comment by nateberkopec** [comment] 2019-10-21 01:45
Closing. If you can create a reproducible example, please open a new issue.

**Closed by nateberkopec** 2019-10-21 01:45 UTC
Labels: needs-repro
