### ISSUE TITLE
Puma Memory abnormal memory consumption

### ISSUE THREAD

**Issue by shirkavand** [puma/puma#1600] opened 2018-06-21 21:14 UTC
I have read several threads related to this topic:

- [Info 1](https://github.com/puma/puma/issues/342)
- [Info 2](https://github.com/puma/puma/issues/1047)
- [info 3](https://github.com/puma/puma/issues/1000)
- [info 4](https://devcenter.heroku.com/articles/ruby-memory-use)
- [Info 5](https://devcenter.heroku.com/articles/tuning-glibc-memory-behavior)
- [Info 6](https://www.schneems.com/2015/05/11/how-ruby-uses-memory.html)
- [Info 7](https://www.levups.com/en/blog/2017/optimize_ruby_memory_usage_jemalloc_heroku_scalingo.html)

a) Some of those links say that the problem is related with Ruby 2.2 and that the problem is fixed on 2.3

b) Some others say that using a Puma-configured-with-jemalloc (along some other tweaks) fix the problem 

c) Some other - in this case heroku users - say that the did nothing and it just started working properly

I am using Ruby 2.4.0p0,  Rails 5.1.6 and Puma 3.11.4 and still see abnormal memory consumption with Puma. 

**Side note:** For testing purposes, i replaced Puma and installed Passenger. Using the same machine, same Rails, Same Ruby, Same JMeter tests for the same period of time, and had no issue at all. This is: The memory usage grows up to a plateau, and when the test finishes the memory return to 150Mb per worker (aprox) 

### Steps to reproduce

There are many ways, one simple way is:

1) Create a Rails app from scratch

2) Create a basic `GET/POST` endpoint (one that only returns head :ok)

3) Start hitting the endpoint using some tool like JMeter for a long period of time

### Expected behavior

The memory usage grows up to a plateau, and when the test finishes the memory return to 150Mb per worker (aprox). This happened locally on my development machine and on Heroku.

### Actual behavior

The memory usage starts to grow and grow and never stops growing. Once the JMeter test finish, the memory never gets to 150Mb (or something) instead stays to the last value reached by the last request made by JMeter (i.e 2Gb per worker aprox). This happened locally on my development machine and on Heroku.

### System configuration

**Ruby version**: 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
**Rails version**: 5.1.6
**Puma version**: 3.11.4

**Comment by njirap** [comment] 2018-07-02 15:16
We have also observed this with almost similar versions
**Puma version:** 3.11.4
**Rails version:** 5.0.3
**Ruby version:** 2.4.1

**Comment by QuantamHD** [comment] 2018-07-31 01:00
Had this issue as well with this as well. The Google Protobuf project also had a similar issue with Ruby 2.2 and was supposedly fixed in 2.3, but the issue could have persisted. In their case, https://github.com/google/protobuf/issues/474, the issue seemed to be related to the ruby method rb_str_cat and by extension in the puma code base rb_str_cat2. These two calls show up only twice in total in the puma code base in **puma_http11.c**:_211-212_

```c
void http_field(puma_parser* hp, const char *field, size_t flen,
                                 const char *value, size_t vlen)
{
  VALUE f = Qnil;
  VALUE v;

  VALIDATE_MAX_LENGTH(flen, FIELD_NAME);
  VALIDATE_MAX_LENGTH(vlen, FIELD_VALUE);

  f = find_common_field_value(field, flen);

  if (f == Qnil) {
    /*
     * We got a strange header that we don't have a memoized value for.
     * Fallback to creating a new string to use as a hash key.
     */

    size_t new_size = HTTP_PREFIX_LEN + flen;
    assert(new_size < BUFFER_LEN);

    memcpy(hp->buf, HTTP_PREFIX, HTTP_PREFIX_LEN);
    memcpy(hp->buf + HTTP_PREFIX_LEN, field, flen);

    f = rb_str_new(hp->buf, new_size);
  }

  /* check for duplicate header */
  v = rb_hash_aref(hp->request, f);

  if (v == Qnil) {
      v = rb_str_new(value, vlen);
      rb_hash_aset(hp->request, f, v);
  } else {
      /* if duplicate header, normalize to comma-separated values */
      rb_str_cat2(v, ", ");
      rb_str_cat(v, value, vlen);
  }
}
```

The Protobuf team created an alternate implementation which did not leak memory shown below
```c
// This function is equivalent to rb_str_cat(), but unlike the real
// rb_str_cat(), it doesn't leak memory in some versions of Ruby.
// For more information, see:
//   https://bugs.ruby-lang.org/issues/11328
VALUE noleak_rb_str_cat(VALUE rb_str, const char *str, long len) {
  size_t oldlen = RSTRING_LEN(rb_str);
  rb_str_modify_expand(rb_str, len);
  char *p = RSTRING_PTR(rb_str);
  memcpy(p + oldlen, str, len);
  rb_str_set_len(rb_str, oldlen + len);
}
``` 

Puma version: 3.12.0
Rails: 5.1.6
Ruby: 2.3.7

**Comment by shirkavand** [comment] 2018-09-18 22:11
@QuantamHD thanks for the reply, can you give me more guidance about what are the next steps to follow based on your answer?  Do i have to patch the code with Protobuf's version somehow?

**Comment by 1c7** [comment] 2019-01-25 07:08
@shirkavand have you solve your problem?
it's been 4 months now (2018,9~2019,1)

**Comment by shirkavand** [comment] 2019-02-26 20:47
@1c7 no, at the end we switched - sadly - to passenger. We found no way to avoid this memory leak. I know some new versions of puma have been released, but we have not tested those yet.

Do you have any insight of wether these new versions solve the problem or not?

**Comment by 1c7** [comment] 2019-02-27 01:16
@shirkavand 
I am on subway now. reply you later

**Comment by wjordan** [comment] 2019-02-27 01:51
I tried and failed to reproduce the original issue as described. I ran a local load-test against a `rails new` project with a simple `head :ok` controller-action, running a local-development Puma server (`bin/rails s`), testing with [wrk](https://github.com/wg/wrk) (`wrk http://0.0.0.0:3000/test/test -d 60 -t 50 -c 50`) on Ubuntu 18.04, Ruby 2.4.1, Puma 3.11.4, and Rails 5.1.6. RSS remained constant around ~64MB throughout the length of the load-test.

What's missing is a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) that reliably reproduces the issue across a broader range of environments. Until more specific steps can be found, it could very well be any number of other issues, unrelated to Puma, that could be causing abnormal memory growth in specific applications/environments.

**Comment by 1c7** [comment] 2019-02-27 02:45
Hi @shirkavand 
> Do you have any insight of whether these new versions solve the problem or not?

I am using Rails 5.2.2, Ruby 2.5.1
I haven't try to reproduce what you describe. like @wjordan  did.  

## But I have a story for you (it's about Docker) (it may help, not sure) 

After I type it all out, I realize it may be too long. so if you don't want read all of that, just use Docker

You can write config in `docker-compose.yml` to limit memory usage, 
And add healthcheck to restart it automatically if somehow it crash.
You can think of Docker as `poor man's Heroku` haha.  
Even though Docker is much much more than that.

Docker is free and even you are only 1 person+1 production machine. you should still use it.
Docker is not big or difficult to learn. (kubernetes is difficult, but not docker&docker swarm)

## Story begin: 
Couple months ago I was trying to do 0 downtime deployment
(or blue/green deployment, same things)
by the way I use `mina`, not `cap`

**Comment by 1c7** [comment] 2019-02-27 02:46
## First Try:  Puma `Phased Restart`

* Machine A: works perfectly
       Which mean it can restart without downtime within 5-15 seconds

* Machine B: Fail. (Machine B is production server)
         Mean that each time puma restarts, it take 100% CPU for 2-5 minute.

### I try to work out what's the difference between A and B.

* Environments variable? `LANG=en_US.utf8`
* Puma config file (Am I config the worker number right? preload_app? what's that?)

I tried everything, everything I can think of.  Can't solve it.
I just tire of this. I don't care. I just want it up and running. 

### (Insert memes here) 
Mission Impossible 6 meme: "Why do you have to make things so fucking complicated?"
(Henry Cavill yelling to that bad guy)
(Disclaminer: I still thanks people behind puma open source project, I am just mad at the problem itself. not the people behind the project)

### So I just ran 2 copy of Rails on production server

* One on port 9292
* One on port 9696

it didn't solve that 2-5 minute 100% CPU start-up time.
but I just don't care, I have to move on.    

And I use Nginx load balancer. config look like this:   
```
upstream app_witt {
  server 127.0.0.1:9292;
  # server 127.0.0.1:9696;
}
```
You can see `#` here, 
because I just switch 9292 and 9696 back and forth.
Manually change Nginx config and apply config with`sudo nginx -s reload`

Conclusion: Mina + Nginx + Puma

### It work OK for a while. until I tire of it.
it's just a stuipd & tempoary solution.

Every time I want to deploy.

* ssh to server
* `kill -9 [PID]` and restart the other Rails app
* Change Nginx config, point to that Rails app. apply Nginx config

It is very manual and cost me at least 5 minute.
After doing that for 100+ time. I am just sick of it.

**Comment by 1c7** [comment] 2019-02-27 02:46
### Second Try: Passenger
Passenger work OK. start fast. like 5 to 10 second.    
but 0 downtime need enterprise passenger.

Conclusion: Mina + Nginx + Passenger
Still not solving the real issue here: deployment is too manual, very annoying

### Third Try: Docker

**Comment by 1c7** [comment] 2019-02-27 03:12
## Third Try: Docker

**Comment by 1c7** [comment] 2019-02-27 03:28
## I hope what I wrote to provide some value 
And not being seen as some guys on the internet wrote a long ranting.

I should put these into my blog: 1c7.me for better SEO haha

**Comment by nateberkopec** [comment] 2019-02-28 14:24
99% of memory "leak" issues in Ruby are:

1. [Fragmentation.](https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html)
2. [An old C extension in your dependencies.](https://github.com/ASoftCo/leaky-gems).

There are already several things in this thread that make me think that many of you are seeing thread-related fragmentation:

> For testing purposes, i replaced Puma and installed Passenger.

You replaced a multi-threaded application server with a single-threaded one (I'm assuming you would have said something specifically if you were using Passenger Enterprise, which allows threads). This eliminates the majority of memory fragmentation in Ruby.

> We have also observed this with almost similar versions but on Ubuntu 16.04. OSX does not have this.

The fragmentation issue linked to above seems to be much worse on Linux than on Mac, possibly due to OSX shipping older versions of `malloc` or possibly just better memory management in the Mach kernel. Many BSD-based operating systems also do not report fragmentation issues w/Ruby.

I must close this issue, as without a minimal verifiable example, we can't do anything about it. I've fixed memory "leak" issues on dozens of Puma applications, and they all come down to the two issues I mentioned at the beginning.

**Closed by nateberkopec** 2019-02-28 14:24 UTC

**Comment by alpracka** [comment] 2020-02-21 10:18
Just want to share good experience with jemalloc 5.1 (so far). I was searching for memory issues as the usage was huge in my eyes. Running Debian 10, Ruby 2.6.5, 4x CPU, 8GB RAM, 3x **Puma** 👍 workers with 8 to 16 threads, kind of project management app.

![Screenshot 2020-02-21 at 10 41 59](https://user-images.githubusercontent.com/1401799/75023844-c845c800-5498-11ea-8d46-605c8ef4f74d.png)

Setting jemalloc in my case [1]:

``` shell
# Debian 10 + ruby-install
$ apt-get install libjemalloc2 libjemalloc-dev
$ ruby-install ruby-2.6.5 -- --with-jemalloc
```
Influenced by [2].

1: https://github.com/postmodern/ruby-install
2: https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat/

**Comment by h0jeZvgoxFepBQ2C** [comment] 2021-01-23 18:09
Setting MALLOC_ARENA_MAX to 2 changed the contantly-growing memory consumtion to a flat graph in our system (with 50% less memory consumption in the end). Thank you so much, maybe you should even output the current MALLOC_ARENA_MAX setting when starting puma, so more people are getting aware of this. Thank you!!!
