### ISSUE TITLE
Puma 3.7.0 undefined symbol: OPENSSL_init_ssl

### ISSUE THREAD

**Issue by vadimskrotsky** [puma/puma#1205] opened 2017-02-01 11:19 UTC
### Steps to reproduce

Upgrade Puma from 3.6.0 to 3.7.0 in rails app.

### Expected behavior

It should serve when `bundle exec puma ...` up like with version 3.6.0.

### Actual behavior

`symbol lookup error: /var/www/app/shared/bundle/ruby/2.3.0/gems/puma-3.7.0/lib/puma/puma_http11.so: undefined symbol: OPENSSL_init_ssl
`

### System configuration

**Ruby version**: 2.3.1p112
**Rails version**: 5.0.1
**OpenSSL**: 1.1.0 (25 Aug 2016)
**OS**: Debian GNU/Linux 8 (jessie) Linux 3.16.0-4-amd64

**Comment by deepj** [comment] 2017-02-04 15:14
@vadimskrotsky OpenSSL 1.1.0 is fully supported since Ruby 2.4 (see https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/). So I guess the problem lies in that.

**Comment by waltercool** [comment] 2017-02-08 17:11
This version also makes problem with LibreSSL. 3.6.0 was fine.

Attaching compilation error.

[gem_make.txt](https://github.com/puma/puma/files/761380/gem_make.txt)

**Comment by nateberkopec** [comment] 2017-02-09 14:46
Dupe of #1181.

**Closed by nateberkopec** 2017-02-09 14:46 UTC

**Comment by nibygro** [comment] 2017-08-29 12:44
@nateberkopec have the same issue, but with 3.10

> $ openssl version
> OpenSSL 1.1.0f  25 May 2017
> $ rails s
> => Booting Puma
> => Rails 5.1.3 application starting in development on http://localhost:3000
> => Run `rails server -h` for more startup options
> /home/nikolai/.rvm/rubies/ruby-2.4.1/bin/ruby: symbol lookup error: /home/nikolai/.rvm/gems/ruby-2.4.1/gems/puma-3.10.0/lib/puma/puma_http11.so: undefined symbol: OPENSSL_init_ssl

Where I can read how to fix it? #1181 doesn't help

**Comment by nateberkopec** [comment] 2017-08-29 14:21
@nibygro You need `openssl-dev` installed.

**Comment by nibygro** [comment] 2017-08-29 14:25
@nateberkopec you mean  `libssl-dev` ? Already installed:

> $ sudo apt-get install libssl-dev
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> libssl-dev is already the newest version (1.0.2g-1ubuntu4.8).

> $ dpkg -s libssl-dev
> Package: libssl-dev
> Status: install ok installed
> Priority: optional
> Section: libdevel
> Installed-Size: 7027
> Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
> Architecture: amd64
> Multi-Arch: same
> Source: openssl
> Version: 1.0.2g-1ubuntu4.8
> Depends: libssl1.0.0 (= 1.0.2g-1ubuntu4.8), zlib1g-dev
> ...

Maybe some symlinks are broken?

**Comment by nibygro** [comment] 2017-08-29 15:52
Nevermind. Fixed by recompiling openssl with ` ./configure CFLAGS=-fPIC CXXFLAGS=-fPIC`

Thanx!
