### ISSUE TITLE
pumactl phased-restart release number does not update after deploy but the latest code is being used

### ISSUE THREAD

**Issue by andresbarcenas** [puma/puma#1860] opened 2019-07-23 19:10 UTC
### Steps to reproduce

1) Using Capistrano, the latest code is pushed and symlinked to current (See below command that capistrano executes to run a phased-restart

```
 INFO [31fea8e9] Running /usr/local/rvm/bin/rvm 2.5.0 do bundle exec pumactl -S /home/deployer/apps/stern/shared/tmp/pids/puma.state -F /home/deployer/apps/stern/releases/20190723185955/config/puma.rb phased-restart as deployer@mdlqa2.mdlive.com
 DEBUG [31fea8e9] Command: cd /home/deployer/apps/stern/current && ( export RACK_ENV="staging" ; /usr/local/rvm/bin/rvm 2.5.0 do bundle exec pumactl -S /home/deployer/apps/stern/shared/tmp/pids/puma.state -F /home/deployer/apps/stern/releases/20190723185955/config/puma.rb phased-restart )
```

# This is the puma log that shows when the phased restart occurs:
```
[126607] - Starting phased worker restart, phase: 1
[126607] + Changing to /home/deployer/apps/stern/current
[126607] - Stopping 126613 for phased upgrade...
[126607] - TERM sent to 126613...
[24150] + Gemfile in context: /home/deployer/apps/stern/releases/20190723185955/Gemfile
[126607] - Worker 0 (pid: 24150) booted, phase: 1
[126607] - Stopping 126617 for phased upgrade...
[126607] - TERM sent to 126617...
[24182] + Gemfile in context: /home/deployer/apps/stern/releases/20190723185955/Gemfile
[126607] - Worker 1 (pid: 24182) booted, phase: 1
```

# This is parent process that is still referencing the old deployment ID ending in 625
```
deployer 126607  0.0  0.2 413076 17232 ?        Sl   14:58   0:00 puma 4.0.1 (unix:///home/deployer/apps/stern/shared/tmp/sockets/puma.sock) [20190723185625]
```
# There are 2 worker processes that are also referencing the old deployment ID ending in 625
```
deployer  24150  3.0  2.8 1474144 204936 ?      Sl   15:01   0:07 puma: cluster worker 0: 126607 [20190723185625]
deployer  24182  3.1  2.8 1474028 204632 ?      Sl   15:01   0:07 puma: cluster worker 1: 126607 [20190723185625]
```
# Running lsof -p on Process ID 24150, it shows that it is running on 20190723185955 but when running ps aux, it shows the old release ID 20190723185625

```
[deployer@mdlqav2s2 current]$ lsof -p 24150
COMMAND   PID     USER   FD      TYPE             DEVICE  SIZE/OFF     NODE NAME
ruby    24150 deployer  cwd       DIR                8,2      4096 17261402 /home/deployer/apps/stern/releases/20190723185955
ruby    24150 deployer  rtd       DIR                8,2      4096       64 /
```

### System configuration
CentOS 7.4

**Ruby version**: 2.5.0 
**Rails version**: 5.2.2
**Puma version**: 4.0.1

**Comment by magec** [comment] 2019-07-30 13:54
Same behavior here, also, a zombie process is left out for each 'phased-restarted' worker, old workers are not waited by the cluster.

```
11510  0.8  0.2  81836 17256 ?        Ssl  13:48   0:01 puma 4.0.1 (tcp://0.0.0.0:8081) [20190730133629]
11558  7.8  0.0      0     0 ?        Z    13:48   0:14  \_ [ruby] <defunct>
11560  7.8  0.0      0     0 ?        Z    13:48   0:14  \_ [ruby] <defunct>
12545 87.6  2.7 380240 216076 ?       Rl   13:51   0:08  \_ puma: cluster worker 0: 11510 [20190730133629]
12549 89.7  2.7 376144 215424 ?       Rl   13:51   0:08  \_ puma: cluster worker 1: 11510 [20190730133629]
```

**Comment by andresbarcenas** [comment] 2019-08-15 18:40
@magec Just FYI, The defunct processes issue is addressed on version 4.1.0

**Comment by truongduyng** [comment] 2019-09-24 12:07
I also meet this problem on version 4.2.0 Pls help tp take a look

**Comment by nateberkopec** [comment] 2019-09-24 13:55
Needs a reproducing case/test, but it seems pretty likely that this could happen, given the implementation of infer_tag/how cap is setting tags.

Please post your configuration, specifically are you setting the tag manually in it? Does capistrano set the tag somehow (?)

**Comment by truongduyng** [comment] 2019-09-25 06:31
here is my puma config
```
#!/usr/bin/env puma

directory '/home/deploy/sporta/current'
rackup "/home/deploy/sporta/current/config.ru"
environment 'production'

tag ''

pidfile "/home/deploy/sporta/shared/tmp/pids/puma.pid"
state_path "/home/deploy/sporta/shared/tmp/pids/puma.state"
stdout_redirect '/home/deploy/sporta/shared/log/puma_error.log', '/home/deploy/sporta/shared/log/puma_access.log', true

threads 4,16

bind 'unix:///home/deploy/sporta/shared/tmp/sockets/puma.sock'

workers 1

prune_bundler

on_restart do
  puts 'Refreshing Gemfile'
  ENV["BUNDLE_GEMFILE"] = "/home/deploy/sporta/current/Gemfile"
end
```
I can get puma work well with stop and start commands but restart didn't work. 
I'm using 
capistrano 3.11.1
puma 4.2.0
capistrano3-puma 4.0.0

**Comment by truongduyng** [comment] 2019-09-26 05:57
I'm sorry. My problem is actually the socket file is removed when restarting. I think the `Inherited unix:///home/deploy/sporta/shared/tmp/sockets/puma.sock` doesn't work. After restarting, my socket file was removed

**Comment by nateberkopec** [comment] 2019-10-21 01:45
Closing. If you can create a reproducible example, please open a new issue.

**Closed by nateberkopec** 2019-10-21 01:45 UTC
Labels: needs-repro, restart

**Comment by lluis** [comment] 2023-07-25 19:00
I am facing the same issue with puma 6.3.0, but I don't know how to create a reproducible example since it implies a lot of pieces and server configuration

this are my relevant config files:

* lib/capistrano/tasks/puma.rake

```
  desc "restart puma"
  task "restart" do
    on roles(fetch(:puma_role)) do
      within current_path do
        with rails_env: fetch(:rails_env) do
          if test "[ -f #{File.join(shared_path, fetch(:puma_pid))} ]" and test :kill, "-0 $( cat #{fetch(:puma_pid)} )"
            puma_cmd = fetch(:puma_phased_restart, true) ? "phased-restart" : "restart"
            execute :pumactl, "-S #{fetch(:puma_state)} #{puma_cmd}"
          else
            #pid file not found, so puma is probably not running or it using another pidfile
            warn 'Puma not running'
          end
        end
      end
    end
  end

  after 'deploy:finished', 'puma:restart'
```

* config/puma.rb

```
rails_env = ENV.fetch('RAILS_ENV', 'development')
current_dir = File.expand_path('../../../current', __dir__)
directory current_dir
rackup "#{current_dir}/config.ru"
environment rails_env
pidfile ENV.fetch('PIDFILE', File.join(current_dir, 'tmp/pids/puma.pid'))
state_path File.join(current_dir, 'tmp/pids/puma.state')
stdout_redirect(
  "#{current_dir}/log/puma.stdout.log",
  "#{current_dir}/log/puma.stderr.log",
  true
)
max_threads_count = ENV.fetch('RAILS_MAX_THREADS', 5)
min_threads_count = ENV.fetch('RAILS_MIN_THREADS', max_threads_count)
threads min_threads_count, max_threads_count
bind "unix://#{current_dir}/tmp/sockets/puma.sock"
workers ENV.fetch('WEB_CONCURRENCY', 1)
prune_bundler
preload_app! false
plugin :tmp_restart
worker_boot_timeout 120
```

* config.ru

```
require_relative "config/environment"
run App::Application
Rails.application.load_server
```

* systemd service:

```
[Unit]
Description=Puma Service
After=network.target

[Service]
Type=notify
WatchdogSec=10
User=deploy
WorkingDirectory=/home/deploy/app/current
Environment=PUMA_DEBUG=0
Environment=RAILS_ENV=production
Environment=GEM_HOME=/home/deploy/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0
Environment=GEM_PATH=/home/deploy/.gem/ruby/3.1.0:/home/deploy/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0
Environment=PATH=/home/deploy/.rbenv/shims:/usr/local/bin:/usr/bin:/bin
ExecStart=/home/deploy/.rbenv/bin/rbenv exec bundle exec --keep-file-descriptors puma -C config/puma.rb
Restart=always

[Install]
WantedBy=multi-user.target
```

And here you can see Puma it's using the old release dir (20230725170540):

```
[deploy@rails7 current]$ cat tmp/pids/puma.state 
---
pid: 252986
running_from: "/home/deploy/app/releases/20230725170540"

[deploy@rails7 current]$ lsof -p 252986 | grep releases
ruby    252986 deploy  cwd       DIR              259,5     4096  537617 /home/deploy/app/releases/20230725180351
```

even after a phased_restart:

```
[deploy@rails7 current]$ bundle exec pumactl -S tmp/pids/puma.state phased-restart
Command phased-restart sent success
[deploy@rails7 current]$ cat tmp/pids/puma.state 
---
pid: 252986
running_from: "/home/deploy/app/releases/20230725170540"
[deploy@rails7 current]$ realpath .
/home/deploy/app/releases/20230725180351
```

* my versions:

```
[deploy@rails7 current]$ bundle show puma
/home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0

[deploy@rails7 current]$ bundle show capistrano
/home/deploy/app/shared/bundle/ruby/3.1.0/gems/capistrano-3.17.3

[deploy@rails7 current]$ bundle show rails
/home/deploy/app/shared/bundle/ruby/3.1.0/gems/rails-7.0.6

[deploy@rails7 current]$ ruby -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]
```

It currently works for some deploys, until it reaches the capistrano keep_releases deploys and the old release dir is deleted, then puma starts failing with:

```
[210221] + Changing to /home/deploy/app/current
[210221] - Stopping 238194 for phased upgrade...
[210221] - TERM sent to 238194...
[247740] ! Unable to start worker
[247740] /home/deploy/app/releases/20230725101307/Gemfile not found
[247740] /home/deploy/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.15/lib/bundler/definition.rb:35:in `build'
    /home/deploy/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.15/lib/bundler.rb:208:in `definition'
    /home/deploy/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.15/lib/bundler.rb:156:in `setup'
    /home/deploy/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.15/lib/bundler/setup.rb:23:in `block in <top (required)>'
    /home/deploy/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.15/lib/bundler/ui/shell.rb:159:in `with_level'
    /home/deploy/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.15/lib/bundler/ui/shell.rb:111:in `silence'
    /home/deploy/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.15/lib/bundler/setup.rb:23:in `<top (required)>'
    <internal:/home/deploy/.rbenv/versions/3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    <internal:/home/deploy/.rbenv/versions/3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/configuration.rb:347:in `rack_builder'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/configuration.rb:366:in `load_rackup'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/configuration.rb:288:in `app'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/runner.rb:169:in `app'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/runner.rb:173:in `start_server'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/cluster/worker.rb:60:in `run'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/cluster.rb:206:in `worker'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/cluster.rb:99:in `block in spawn_worker'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/cluster.rb:99:in `fork'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/cluster.rb:99:in `spawn_worker'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/cluster.rb:81:in `block in spawn_workers'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/cluster.rb:74:in `times'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/cluster.rb:74:in `spawn_workers'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/cluster.rb:163:in `check_workers'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/cluster.rb:436:in `run'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/launcher.rb:194:in `run'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/lib/puma/cli.rb:75:in `run'
    /home/deploy/app/shared/bundle/ruby/3.1.0/gems/puma-6.3.0/bin/puma-wild:25:in `<main>'
```

**Comment by lluis** [comment] 2023-07-28 12:36
The `Gemfile not found error` can be solved by adding to the systemd service:
```
Environment=BUNDLE_GEMFILE=/home/deploy/app/current/current/Gemfile
```

**Comment by nguyenngoc2505** [comment] 2023-12-12 03:44
I've same issue on puma 6.4.0
