### ISSUE TITLE
fork_worker automatic refork never triggers

### ISSUE THREAD

**Issue by slondr** [puma/puma#2985] opened 2022-10-05 12:56 UTC
**Describe the bug**

I have `fork_worker` enabled and was excited to deprecate my hand-spun automatic cluster restart with the built-in automatic refork functionality. However, after a couple months of using `fork_worker` live on production, I have never seen a refork actually occur without manual intervention. On a typical day, my application gets about 40,000 hits, and I have puma configured for a cluster size of 8 workers. I've tried setting the value of the `fork_worker` to as low as 150, which should mean a median of (40k requests divided by 8 workers divided by 1/150 for a time series of reforks per time quanta...) 21 reforks per minute! Yet, I never see the telltale drop in memory usage that I see when I manually send SIGURG to the cluster, never see any of the typical worker startup messages in the logs, etc. 

**Puma config:**

```ruby
environment 'production'
workers 8
threads 1, 7
fork_worker 150
plugin :tmp_restart
bind 'unix:///path/to/server.sock'
activate_control_app 'unix://path/to/socket.sock', auth_token: 'hello world'
pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }
```
I launch puma via systemd, with the command `RAILS_ENV=production bundle exec --keep-file-descriptors puma`.

**Comment by MSP-Greg** [comment] 2022-10-05 14:23
@slondr

I think more data might be helpful.  I set fork_worker to 1000, and threw a wrk stream at a server, and it did restart, so I'm not sure what the issue is (yet).  That was using master, not a release.

> 21 reforks per minute!

You might check that, I think the number should be more like a refork once every 43 minutes?  40k/(8*24) = 208 req per hour per worker...

**Comment by slondr** [comment] 2022-10-05 14:25
Oh yeah, worth mentioning this is on puma 5.6.4 — though I don't see anything in the 5.6.5 release notes that I think would change this? I'll go test that + master with my application to see if it does.

**Comment by MSP-Greg** [comment] 2022-10-05 14:34
@slondr

Most of my local test code is for master; I probably should have checked 5.6.5 or 5.6.4.  I'll check a release sometime soon...

**Comment by slondr** [comment] 2022-10-06 13:22
I was looking into this more today and checked my `pumactl stats`. It looks like workers 1 through 7 each have thousands of requests served but worker 0 only has _21_. I'm guessing that's why I never see a refork. It's weird that this is so consistent though. I don't really know how Puma's scheduling system works for cluster mode but this definitely doesn't seem right to me.

**Comment by dentarg** [comment] 2023-07-03 05:37
@slondr still having this issue? are you able to reproduce it for us if so?

**Comment by rus-max** [comment] 2024-01-24 07:22
This will enable automatic fork

```ruby        
# Auto-fork after the specified number of requests.
if (fork_requests = @options[:fork_worker].to_i) > 0
  @events.register(:ping!) do |w|
    fork_worker! if w.index == 0 &&
      w.last_status[:requests_count] >= fork_requests * (w.phase + 1)
  end
end
```

**Comment by rus-max** [comment] 2024-01-30 07:22
Auto-fork after the specified number of requests always. [Commit](https://github.com/rus-max/puma/commit/3734e30991c7c089dfabc0541164cf93dfe1b8ce)

**Comment by bogn83** [comment] 2024-06-17 08:39
For my local benchmarking tests, the issue was that keep alive led to all requests going to one worker. Once I was no longer using keep alive requests got balanced.

**Comment by nateberkopec** [comment] 2024-08-06 22:40
2 years with no repro, closing.

**Closed by nateberkopec** 2024-08-06 22:40 UTC
Labels: needs-repro
