### ISSUE TITLE
Puma 6.0 seems to break Turbo Streams and/or Websockets

### ISSUE THREAD

**Issue by miharekar** [puma/puma#3003] opened 2022-10-26 06:17 UTC
**Describe the bug**

The issue seems related to #2962, and I see [other people encountered it too](https://www.reddit.com/r/ruby/comments/y9vcdy/comment/ita01po/) but do not see it discussed here, which is why I opened this issue.

**Puma config:**

[Puma config](https://github.com/miharekar/decent-visualizer/blob/main/config/puma.rb)
Command line options: `bin/rails s`

**To Reproduce**
Basically the code before [this commit](https://github.com/miharekar/decent-visualizer/commit/f57ca90239a3c942f6f1346e4465d6b740a74a5c). It is constantly crashing websockets. Both local and on Heroku production.

I imagine it's simply creating `turbo_stream_from` in a Rails app that breaks it.

It's hard to describe what exactly happens because it seems it's not in the logs. But whenever I change a file and reload the page, the browser hangs. This is all that's in the logs at the time:

```
Finished "/cable" [WebSocket] for ::1 at 2022-10-26 08:12:05 +0200
Turbo::StreamsChannel stopped streaming from Z2lkOi8vZGVjZW50LXZpc3VhbGl6ZXIvVXNlci9mYmRiNTJmZS1jYWI5LTRjNDgtODU3Yi03NmNmZTZlNDUxMzg:shots
Started GET "/assets/es-module-shims.js-f913aa9a2196b2d319bed837931bcd4e6c4b411c.map" for ::1 at 2022-10-26 08:12:05 +0200
Started GET "/cable" for ::1 at 2022-10-26 08:12:05 +0200
Started GET "/cable" [WebSocket] for ::1 at 2022-10-26 08:12:05 +0200
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Turbo::StreamsChannel is transmitting the subscription confirmation
Turbo::StreamsChannel is streaming from Z2lkOi8vZGVjZW50LXZpc3VhbGl6ZXIvVXNlci9mYmRiNTJmZS1jYWI5LTRjNDgtODU3Yi03NmNmZTZlNDUxMzg:shots
```

But if I keep refreshing, eventually it'll come through. Many of these will be in the browser console soon afterwards:

<img width="928" alt="CleanShot 2022-10-26 at 08 16 18@2x" src="https://user-images.githubusercontent.com/986645/197949090-941b1c1f-9a3d-4538-b29a-c238c8759948.png">

<img width="933" alt="CleanShot 2022-10-26 at 08 14 25@2x" src="https://user-images.githubusercontent.com/986645/197948845-86cf7472-4b7a-47f7-abce-b85e5a62cd62.png">

and in logs:
```
Started GET "/assets/es-module-shims.js-f913aa9a2196b2d319bed837931bcd4e6c4b411c.map" for ::1 at 2022-10-26 08:15:52 +0200
Finished "/cable" [WebSocket] for ::1 at 2022-10-26 08:17:50 +0200
Started GET "/cable" for ::1 at 2022-10-26 08:17:50 +0200
Started GET "/cable" [WebSocket] for ::1 at 2022-10-26 08:17:50 +0200
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Started GET "/cable" for 127.0.0.1 at 2022-10-26 08:19:09 +0200
Started GET "/cable" [WebSocket] for 127.0.0.1 at 2022-10-26 08:19:09 +0200
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable" [WebSocket] for ::1 at 2022-10-26 08:19:21 +0200
Started GET "/cable" for ::1 at 2022-10-26 08:19:21 +0200
Started GET "/cable" [WebSocket] for ::1 at 2022-10-26 08:19:21 +0200
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable" [WebSocket] for 127.0.0.1 at 2022-10-26 08:19:29 +0200
Started GET "/cable" for 127.0.0.1 at 2022-10-26 08:19:29 +0200
Started GET "/cable" [WebSocket] for 127.0.0.1 at 2022-10-26 08:19:29 +0200
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable" [WebSocket] for ::1 at 2022-10-26 08:19:37 +0200
Started GET "/cable" for ::1 at 2022-10-26 08:19:37 +0200
Started GET "/cable" [WebSocket] for ::1 at 2022-10-26 08:19:37 +0200
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable" [WebSocket] for 127.0.0.1 at 2022-10-26 08:19:47 +0200
Started GET "/cable" for 127.0.0.1 at 2022-10-26 08:19:47 +0200
Started GET "/cable" [WebSocket] for 127.0.0.1 at 2022-10-26 08:19:47 +0200
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
```

**Comment by miharekar** [comment] 2022-10-26 06:24
99% sure #3002 fixes the issue. Can't reproduce it locally anymore, gonna test in prod.

**Comment by nateberkopec** [comment] 2022-10-26 06:24
Thanks for the report. This is a duplicate of #2999, let's move the discussion there.

**Closed by nateberkopec** 2022-10-26 06:24 UTC
